
kademe={
    "akim1":0.0,
    "akim2":0.0,
    "cap1":0.0,
    "cap2":0.0,
    "spir1":0.0,
    "kesit1":0.0,
    "spir2":0.0,
    "voltaj":0.0,
    "bos1":"",
    "bos2": "",
    "bos3": "", 
    "teltipi": "", 
    "folyotel11":0.0,
    "folyotel12":0.0,
    "folyotel21":0.0,
    "folyotel22":0.0,
    "folyotel31":0.0,
    "folyotel32":0.0,
    "folyotel41":0.0,
    "folyotel42":0.0,
    "kapton1":0.0,
    "kapton2":0.0,
    "kapton3":0.0,
    "kapton4":0.0,
    "karetel11":0.0,
    "karetel12":0.0,
    "karetel21":0.0,
    "karetel22":0.0,
    "karetel31":0.0,
    "karetel32":0.0,
    "karetel41":0.0,
    "karetel42":0.0,
    "bos4": "",
    "kademeadi": "",
    "kesit2":0.0,
    "tel_en":0.0,
    "tel_yuk":0.0,
    "spirkat":0.0,
    "kat":0.0,
    "katbosluk":0.0,
    "tel_uzunluk":0.0,
    "tel_agirlik":0.0,
    "sarim_yukseklik":0.0,
    "sonkat_spir":0.0,
    "spir_man":False,
    "bos5": "",
    "bos6": "",
    "bos7": "",
    "bos8": "",
    "check_spir_man":False,
    "kesit_ok":True,
    "kesit_error":True,
    "akim_ok":True,
    "akim_error":True,
    "mancap_1":0.0,
    "mancap_2":0.0,
    "mancap_3":0.0,
    "mancap_4":0.0,
    "mlz_tel_1":"",
    "mlz_tel_2":"",
    "mlz_tel_3":"",
    "mlz_tel_4":"",
    "mlz_karetel_1":"",
    "mlz_karetel_2":"",
    "mlz_karetel_3":"",
    "mlz_karetel_4":"",
    "mlz_folyotel_1":"",
    "mlz_folyotel_2":"",
    "mlz_folyotel_3":"",
    "mlz_folyotel_4":"",
    "mlz_kapton_1":"",
    "mlz_kapton_2":"",
    "mlz_kapton_3":"",
    "mlz_kapton_4":"",
    "gb_check_tel_1" :False,
    "gb_check_tel_2" :False,
    "gb_check_tel_3" :False,
    "gb_check_tel_4" :False,
    "gb_check_karetel_1" :False,
    "gb_check_karetel_2" :False,
    "gb_check_karetel_3" :False,
    "gb_check_karetel_4" :False,
    "gb_check_folyotel_1" :False,
    "gb_check_folyotel_2" :False,
    "gb_check_folyotel_3" :False,
    "gb_check_folyotel_4" :False,
    "gb_check_kapton_1" :False,
    "gb_check_kapton_2" :False,
    "gb_check_kapton_3" :False,
    "gb_check_kapton_4" :False,
    "agr_tel_1":0.0,
    "agr_tel_2":0.0,
    "agr_tel_3":0.0,
    "agr_tel_4":0.0,
    "agr_karetel_1":0.0,
    "agr_karetel_2":0.0,
    "agr_karetel_3":0.0,
    "agr_karetel_4":0.0,
    "agr_folyo_1":0.0,
    "agr_folyo_2":0.0,
    "agr_folyo_3":0.0,
    "agr_folyo_4":0.0,
    "agr_kapton_1":0.0,
    "agr_kapton_2":0.0,
    "agr_kapton_3":0.0,
    "agr_kapton_4":0.0,
    
    }
list1 ={
    "kademe1": 0.0, "kademe2": 0.0, "kademe3": 0.0, "kademe4": 0.0, "kademe5": 0.0, "kademe6": 0.0, "kademe7": 0.0, "kademe8": 0.0, "kademe9": 0.0, "kademe10": 0.0}

recete_veri =  {
    "recete_ID" : 0,
    "musteri_adi" : "",
    "musteri_kodu" : "",
    "siparis_kodu" :"",
    "primer_kademe" : 0,
    "sekonder_kademe" : 0,
    "va_kademe" : 0,
    "primer_group_list" :[kademe for i in range(10)] ,
    "sekonder_group_list" :[kademe for i in range(10)] ,
    "va_group_list" :[[kademe for i in range(10)] for i in range(10)],
    "va_guclist" :[0.0 for i in range(10)],
    "va_altkademe" :[0 for i in range(10)],
    "va_enabled" :False,
    "sac_tipi" : "",
    "guc" : 0.0,
    "gauss" : 0.0,
    "sac" : 0.0,
    "c_sac" : 0.0,
    "frekans" : 0.0,
    "nuve_bosluk" :0.0,
    "karkas": {"adi":"","en":0.0,"boy":0.0,"yukseklik":0.0,"verim":0.0},
    "klemens":{"adi":"","en":0.0,"boy":0.0,"yukseklik":0.0,"akim" :0.0},
    "ayak":{"adi":"","en":0.0,"boy":0.0,"yukseklik":0.0},
    "primer_izo_deg" : 0.0,
    "sekonder_izo_deg" : 0.0,
    "pri_sek_izo_deg" : 0.0,
    "ekran_izo_deg" : 0.0,
    "ekstra_izo_deg" : 0.0,
    "primer_izo_tur" : 0,
    "sekonder_izo_tur" : 0,
    "pri_sek_izo_tur" : 0,
    "ekran_sec" : False,
    "ekstra" : False,
    "trafo_tipi":"",
    "kullanici":"",
    "alAkimYog":0.0,
    "alYogunluk":0.0,
    "cuAkimYog":0.0,
    "cuYogunluk":0.0,
    "diAkimYog":0.0,
    "diYogunluk":0.0,
    "sacYogunluk":0.0,
}   
malzeme_listesi = {"teller":{
                    "mlz_tel_1":"agr_tel_1",
                    "mlz_tel_2":"agr_tel_2",
                    "mlz_tel_3":"agr_tel_3",
                    "mlz_tel_4":"agr_tel_4",
                    "mlz_karetel_1":"agr_karetel_1",
                    "mlz_karetel_2":"agr_karetel_2",
                    "mlz_karetel_3":"agr_karetel_3",
                    "mlz_karetel_4":"agr_karetel_4",
                    "mlz_folyotel_1":"agr_folyo_1",
                    "mlz_folyotel_2":"agr_folyo_2",
                    "mlz_folyotel_3":"agr_folyo_3",
                    "mlz_folyotel_4":"agr_folyo_4",
                    "mlz_kapton_1":"agr_kapton_1",
                    "mlz_kapton_2":"agr_kapton_2",
                    "mlz_kapton_3":"agr_kapton_3",
                    "mlz_kapton_4":"agr_kapton_4"},
                     "agirlik"  :{
                    "agr_tel_1":0.0,
                    "agr_tel_2":0.0,
                    "agr_tel_3":0.0,
                    "agr_tel_4":0.0,
                    "agr_karetel_1":0.0,
                    "agr_karetel_2":0.0,
                    "agr_karetel_3":0.0,
                    "agr_karetel_4":0.0,
                    "agr_folyo_1":0.0,
                    "agr_folyo_2":0.0,
                    "agr_folyo_3":0.0,
                    "agr_folyo_4":0.0,
                    "agr_kapton_1":0.0,
                    "agr_kapton_2":0.0,
                    "agr_kapton_3":0.0,
                    "agr_kapton_4":0.0,
                    },
                }