# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'reciepe.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt,QDate)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(962, 549)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QIcon()
        icon.addFile(u":/C:/Users/YBEKTAS/Desktop/Python/Projeler/Transformator_Calculate/software/source/staticfiles/icons/repport.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(11, 120, 941, 160))
        self.tabWidget_2 = QTabWidget(self.groupBox_3)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(110, 93, 821, 61))
        palette = QPalette()
        brush = QBrush(QColor(239, 239, 239, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        self.tabWidget_2.setPalette(palette)
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.lineEdit_sva1 = QLineEdit(self.tab_3)
        self.lineEdit_sva1.setObjectName(u"lineEdit_sva1")
        self.lineEdit_sva1.setEnabled(False)
        self.lineEdit_sva1.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_sva2 = QLineEdit(self.tab_4)
        self.lineEdit_sva2.setObjectName(u"lineEdit_sva2")
        self.lineEdit_sva2.setEnabled(False)
        self.lineEdit_sva2.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.lineEdit_sva3 = QLineEdit(self.tab_5)
        self.lineEdit_sva3.setObjectName(u"lineEdit_sva3")
        self.lineEdit_sva3.setEnabled(False)
        self.lineEdit_sva3.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.lineEdit_sva4 = QLineEdit(self.tab_6)
        self.lineEdit_sva4.setObjectName(u"lineEdit_sva4")
        self.lineEdit_sva4.setEnabled(False)
        self.lineEdit_sva4.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.lineEdit_sva5 = QLineEdit(self.tab_7)
        self.lineEdit_sva5.setObjectName(u"lineEdit_sva5")
        self.lineEdit_sva5.setEnabled(False)
        self.lineEdit_sva5.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.lineEdit_sva6 = QLineEdit(self.tab_8)
        self.lineEdit_sva6.setObjectName(u"lineEdit_sva6")
        self.lineEdit_sva6.setEnabled(False)
        self.lineEdit_sva6.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.lineEdit_sva7 = QLineEdit(self.tab_9)
        self.lineEdit_sva7.setObjectName(u"lineEdit_sva7")
        self.lineEdit_sva7.setEnabled(False)
        self.lineEdit_sva7.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.lineEdit_sva8 = QLineEdit(self.tab_10)
        self.lineEdit_sva8.setObjectName(u"lineEdit_sva8")
        self.lineEdit_sva8.setEnabled(False)
        self.lineEdit_sva8.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.lineEdit_sva9 = QLineEdit(self.tab_11)
        self.lineEdit_sva9.setObjectName(u"lineEdit_sva9")
        self.lineEdit_sva9.setEnabled(False)
        self.lineEdit_sva9.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.lineEdit_sva10 = QLineEdit(self.tab_12)
        self.lineEdit_sva10.setObjectName(u"lineEdit_sva10")
        self.lineEdit_sva10.setEnabled(False)
        self.lineEdit_sva10.setGeometry(QRect(0, 0, 811, 24))
        self.tabWidget_2.addTab(self.tab_12, "")
        self.line_3 = QFrame(self.groupBox_3)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-3, 48, 951, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.groupBox_3)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 80, 951, 20))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.lineEdit_primer = QLineEdit(self.groupBox_3)
        self.lineEdit_primer.setObjectName(u"lineEdit_primer")
        self.lineEdit_primer.setEnabled(False)
        self.lineEdit_primer.setGeometry(QRect(110, 30, 811, 24))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 30, 61, 20))
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 60, 81, 20))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 120, 91, 20))
        self.lineEdit_sekonder = QLineEdit(self.groupBox_3)
        self.lineEdit_sekonder.setObjectName(u"lineEdit_sekonder")
        self.lineEdit_sekonder.setEnabled(False)
        self.lineEdit_sekonder.setGeometry(QRect(110, 62, 811, 24))
        self.tableWidget = QTableWidget(Dialog)
        if (self.tableWidget.columnCount() < 16):
            self.tableWidget.setColumnCount(16)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, __qtablewidgetitem15)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 324, 941, 181))
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, -2, 361, 121))
        self.label_56 = QLabel(self.groupBox)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(270, 29, 31, 20))
        self.doubleSpinBox_ID = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ID.setObjectName(u"doubleSpinBox_ID")
        self.doubleSpinBox_ID.setEnabled(False)
        self.doubleSpinBox_ID.setGeometry(QRect(300, 29, 51, 24))
        palette1 = QPalette()
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush2 = QBrush(QColor(159, 159, 159, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        brush3 = QBrush(QColor(118, 118, 118, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 128))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.doubleSpinBox_ID.setPalette(palette1)
        self.doubleSpinBox_ID.setFont(font)
        self.doubleSpinBox_ID.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_ID.setAutoFillBackground(False)
        self.doubleSpinBox_ID.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_ID.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_ID.setDecimals(0)
        self.doubleSpinBox_ID.setMaximum(9999.000000000000000)
        self.doubleSpinBox_ID.setValue(0.000000000000000)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 56, 91, 20))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 84, 91, 20))
        self.lineEdit_siparis_kodu = QLineEdit(self.groupBox)
        self.lineEdit_siparis_kodu.setObjectName(u"lineEdit_siparis_kodu")
        self.lineEdit_siparis_kodu.setEnabled(True)
        self.lineEdit_siparis_kodu.setGeometry(QRect(110, 84, 241, 24))
        self.lineEdit_musteri_adi = QLineEdit(self.groupBox)
        self.lineEdit_musteri_adi.setObjectName(u"lineEdit_musteri_adi")
        self.lineEdit_musteri_adi.setGeometry(QRect(110, 56, 241, 24))
        self.doubleSpinBox_guc = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_guc.setObjectName(u"doubleSpinBox_guc")
        self.doubleSpinBox_guc.setEnabled(False)
        self.doubleSpinBox_guc.setGeometry(QRect(110, 27, 71, 25))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.doubleSpinBox_guc.setPalette(palette2)
        self.doubleSpinBox_guc.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_guc.setDecimals(0)
        self.doubleSpinBox_guc.setMaximum(100000.000000000000000)
        self.doubleSpinBox_guc.setValue(0.000000000000000)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 30, 61, 16))
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_ara_text1 = QLineEdit(Dialog)
        self.lineEdit_ara_text1.setObjectName(u"lineEdit_ara_text1")
        self.lineEdit_ara_text1.setGeometry(QRect(240, 287, 381, 31))
        self.pushButton_ara = QPushButton(Dialog)
        self.pushButton_ara.setObjectName(u"pushButton_ara")
        self.pushButton_ara.setGeometry(QRect(630, 287, 61, 31))
        self.comboBox_filter1 = QComboBox(Dialog)
        self.comboBox_filter1.addItem("")
        self.comboBox_filter1.addItem("")
        self.comboBox_filter1.addItem("")
        self.comboBox_filter1.addItem("")
        self.comboBox_filter1.addItem("")
        self.comboBox_filter1.setObjectName(u"comboBox_filter1")
        self.comboBox_filter1.setGeometry(QRect(10, 287, 221, 31))
        self.dateEdit = QDateEdit(Dialog)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(700, 288, 151, 31))
        self.dateEdit.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QDate(2020, 10, 1))
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(850, -2, 101, 141))
        self.pushButton_sil = QPushButton(self.groupBox_2)
        self.pushButton_sil.setObjectName(u"pushButton_sil")
        self.pushButton_sil.setGeometry(QRect(10, 106, 80, 31))
        self.pushButton_kaydet = QPushButton(self.groupBox_2)
        self.pushButton_kaydet.setObjectName(u"pushButton_kaydet")
        self.pushButton_kaydet.setGeometry(QRect(10, 66, 81, 31))
        self.pushButton_temizle = QPushButton(self.groupBox_2)
        self.pushButton_temizle.setObjectName(u"pushButton_temizle")
        self.pushButton_temizle.setGeometry(QRect(10, 26, 80, 31))
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(370, 0, 20, 140))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.groupBox_4 = QGroupBox(Dialog)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(390, 0, 291, 121))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 24, 51, 20))
        self.lineEdit_tarih = QLineEdit(self.groupBox_4)
        self.lineEdit_tarih.setObjectName(u"lineEdit_tarih")
        self.lineEdit_tarih.setGeometry(QRect(123, 24, 161, 24))
        self.lineEdit_kullanici = QLineEdit(self.groupBox_4)
        self.lineEdit_kullanici.setObjectName(u"lineEdit_kullanici")
        self.lineEdit_kullanici.setEnabled(False)
        self.lineEdit_kullanici.setGeometry(QRect(123, 54, 161, 24))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 54, 91, 20))
        self.line_2 = QFrame(Dialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(680, 0, 20, 140))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.pushButton_sec = QPushButton(Dialog)
        self.pushButton_sec.setObjectName(u"pushButton_sec")
        self.pushButton_sec.setGeometry(QRect(870, 510, 81, 31))

        self.retranslateUi(Dialog)
        self.lineEdit_musteri_adi.textChanged.connect(self.lineEdit_siparis_kodu.setText)

        self.tabWidget_2.setCurrentIndex(9)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Recete Secim Sayfas\u0131", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Primer ve Sokender Sar\u0131mlar", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"SVA1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"SVA2", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"SVA3", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("Dialog", u"SVA4", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("Dialog", u"SVA5", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("Dialog", u"SVA6", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QCoreApplication.translate("Dialog", u"SVA7", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QCoreApplication.translate("Dialog", u"SVA8", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), QCoreApplication.translate("Dialog", u"SVA9", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), QCoreApplication.translate("Dialog", u"SVA10", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Primer : ", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Sekonder : ", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"VA Dagilim :", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Kullan\u0131c\u0131", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"Musteri Adi", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"Primer Gerilimleri", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"Sekonder Gerilimleri", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"S1 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"S2 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem7 = self.tableWidget.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Dialog", u"S3 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem8 = self.tableWidget.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Dialog", u"S4 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem9 = self.tableWidget.horizontalHeaderItem(9)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Dialog", u"S5 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem10 = self.tableWidget.horizontalHeaderItem(10)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Dialog", u"S6 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem11 = self.tableWidget.horizontalHeaderItem(11)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Dialog", u"S7 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem12 = self.tableWidget.horizontalHeaderItem(12)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Dialog", u"S8 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem13 = self.tableWidget.horizontalHeaderItem(13)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Dialog", u"S9 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem14 = self.tableWidget.horizontalHeaderItem(14)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Dialog", u"S10 Guc/kdm/gerilimler", None));
        ___qtablewidgetitem15 = self.tableWidget.horizontalHeaderItem(15)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("Dialog", u"Tarih", None));
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Musteri Bilgileri", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"ID :", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Musteri Adi :", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Siparis Kodu  :", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"G\u00fc\u00e7 VA :", None))
        self.pushButton_ara.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.comboBox_filter1.setItemText(0, "")
        self.comboBox_filter1.setItemText(1, QCoreApplication.translate("Dialog", u"Musteri_Ad\u0131", None))
        self.comboBox_filter1.setItemText(2, QCoreApplication.translate("Dialog", u"Musteri_kodu", None))
        self.comboBox_filter1.setItemText(3, QCoreApplication.translate("Dialog", u"Siparis_Kodu", None))
        self.comboBox_filter1.setItemText(4, QCoreApplication.translate("Dialog", u"Tarih", None))

        self.dateEdit.setDisplayFormat(QCoreApplication.translate("Dialog", u"yyyy-MM-dd", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Kontrol", None))
        self.pushButton_sil.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.pushButton_kaydet.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_temizle.setText(QCoreApplication.translate("Dialog", u"Temizle", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Kay\u0131t Detaylar", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Tarih : ", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Kullan\u0131c\u0131 :", None))
        self.pushButton_sec.setText(QCoreApplication.translate("Dialog", u"Sec", None))
    # retranslateUi

