# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'kesit_param2.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

import icons_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(525, 679)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.pushButton_kaydet = QPushButton(Dialog)
        self.pushButton_kaydet.setObjectName(u"pushButton_kaydet")
        self.pushButton_kaydet.setGeometry(QRect(440, 645, 81, 31))
        self.pushButton_kaydet_2 = QPushButton(Dialog)
        self.pushButton_kaydet_2.setObjectName(u"pushButton_kaydet_2")
        self.pushButton_kaydet_2.setGeometry(QRect(350, 645, 81, 31))
        self.frame_2 = QFrame(Dialog)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 0, 521, 643))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QFrame.WinPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.groupBox_31 = QGroupBox(self.frame_2)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.groupBox_31.setGeometry(QRect(20, 57, 481, 582))
        self.groupBox_31.setFont(font)
        self.groupBox_31.setLayoutDirection(Qt.LeftToRight)
        self.groupBox_31.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_voltaj = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_voltaj.setObjectName(u"doubleSpinBox_voltaj")
        self.doubleSpinBox_voltaj.setEnabled(True)
        self.doubleSpinBox_voltaj.setGeometry(QRect(67, 10, 70, 25))
        self.doubleSpinBox_voltaj.setBaseSize(QSize(0, 5))
        font1 = QFont()
        font1.setPointSize(7)
        font1.setBold(True)
        font1.setWeight(75)
        self.doubleSpinBox_voltaj.setFont(font1)
        self.doubleSpinBox_voltaj.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_voltaj.setAutoFillBackground(False)
        self.doubleSpinBox_voltaj.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_voltaj.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_voltaj.setDecimals(1)
        self.doubleSpinBox_voltaj.setMaximum(9999.000000000000000)
        self.comboBox_teltipi = QComboBox(self.groupBox_31)
        self.comboBox_teltipi.addItem("")
        self.comboBox_teltipi.addItem("")
        self.comboBox_teltipi.addItem("")
        self.comboBox_teltipi.setObjectName(u"comboBox_teltipi")
        self.comboBox_teltipi.setEnabled(True)
        self.comboBox_teltipi.setGeometry(QRect(67, 40, 70, 24))
        self.comboBox_teltipi.setInsertPolicy(QComboBox.NoInsert)
        self.doubleSpinBox_sipir1 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_sipir1.setObjectName(u"doubleSpinBox_sipir1")
        self.doubleSpinBox_sipir1.setEnabled(False)
        self.doubleSpinBox_sipir1.setGeometry(QRect(67, 70, 70, 25))
        self.doubleSpinBox_sipir1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_sipir1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sipir1.setDecimals(1)
        self.doubleSpinBox_sipir1.setMaximum(9000.000000000000000)
        self.doubleSpinBox_kesit1 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_kesit1.setObjectName(u"doubleSpinBox_kesit1")
        self.doubleSpinBox_kesit1.setEnabled(False)
        self.doubleSpinBox_kesit1.setGeometry(QRect(67, 100, 70, 25))
        font2 = QFont()
        font2.setBold(True)
        font2.setWeight(75)
        font2.setKerning(True)
        self.doubleSpinBox_kesit1.setFont(font2)
        self.doubleSpinBox_kesit1.setFocusPolicy(Qt.WheelFocus)
        self.doubleSpinBox_kesit1.setFrame(True)
        self.doubleSpinBox_kesit1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kesit1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kesit1.setDecimals(3)
        self.doubleSpinBox_kesit1.setMaximum(100000.000000000000000)
        self.doubleSpinBox_cap1 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_cap1.setObjectName(u"doubleSpinBox_cap1")
        self.doubleSpinBox_cap1.setEnabled(False)
        self.doubleSpinBox_cap1.setGeometry(QRect(67, 130, 70, 25))
        self.doubleSpinBox_cap1.setFont(font2)
        self.doubleSpinBox_cap1.setFocusPolicy(Qt.WheelFocus)
        self.doubleSpinBox_cap1.setFrame(True)
        self.doubleSpinBox_cap1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_cap1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_cap1.setDecimals(3)
        self.doubleSpinBox_cap1.setMaximum(100000.000000000000000)
        self.doubleSpinBox_akim1 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_akim1.setObjectName(u"doubleSpinBox_akim1")
        self.doubleSpinBox_akim1.setEnabled(False)
        self.doubleSpinBox_akim1.setGeometry(QRect(67, 160, 70, 25))
        self.doubleSpinBox_akim1.setFont(font2)
        self.doubleSpinBox_akim1.setFocusPolicy(Qt.WheelFocus)
        self.doubleSpinBox_akim1.setFrame(True)
        self.doubleSpinBox_akim1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_akim1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_akim1.setDecimals(3)
        self.doubleSpinBox_akim1.setMaximum(100000.000000000000000)
        self.doubleSpinBox_cap2 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_cap2.setObjectName(u"doubleSpinBox_cap2")
        self.doubleSpinBox_cap2.setEnabled(False)
        self.doubleSpinBox_cap2.setGeometry(QRect(157, 130, 70, 25))
        self.doubleSpinBox_cap2.setFont(font2)
        self.doubleSpinBox_cap2.setFocusPolicy(Qt.WheelFocus)
        self.doubleSpinBox_cap2.setFrame(True)
        self.doubleSpinBox_cap2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_cap2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_cap2.setDecimals(3)
        self.doubleSpinBox_cap2.setMaximum(100000.000000000000000)
        self.doubleSpinBox_akim2 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_akim2.setObjectName(u"doubleSpinBox_akim2")
        self.doubleSpinBox_akim2.setEnabled(False)
        self.doubleSpinBox_akim2.setGeometry(QRect(157, 160, 70, 25))
        self.doubleSpinBox_akim2.setFont(font2)
        self.doubleSpinBox_akim2.setFocusPolicy(Qt.WheelFocus)
        self.doubleSpinBox_akim2.setFrame(True)
        self.doubleSpinBox_akim2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_akim2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_akim2.setDecimals(3)
        self.doubleSpinBox_akim2.setMaximum(100000.000000000000000)
        self.doubleSpinBox_kesit2 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_kesit2.setObjectName(u"doubleSpinBox_kesit2")
        self.doubleSpinBox_kesit2.setEnabled(False)
        self.doubleSpinBox_kesit2.setGeometry(QRect(157, 100, 70, 25))
        self.doubleSpinBox_kesit2.setFont(font2)
        self.doubleSpinBox_kesit2.setFocusPolicy(Qt.WheelFocus)
        self.doubleSpinBox_kesit2.setFrame(True)
        self.doubleSpinBox_kesit2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kesit2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kesit2.setDecimals(3)
        self.doubleSpinBox_kesit2.setMaximum(100000.000000000000000)
        self.doubleSpinBox_sipir2 = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_sipir2.setObjectName(u"doubleSpinBox_sipir2")
        self.doubleSpinBox_sipir2.setEnabled(False)
        self.doubleSpinBox_sipir2.setGeometry(QRect(157, 70, 70, 25))
        self.doubleSpinBox_sipir2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_sipir2.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_sipir2.setDecimals(1)
        self.doubleSpinBox_sipir2.setMaximum(9000.000000000000000)
        self.doubleSpinBox_sipir2.setSingleStep(0.500000000000000)
        self.label_445 = QLabel(self.groupBox_31)
        self.label_445.setObjectName(u"label_445")
        self.label_445.setGeometry(QRect(167, 40, 50, 21))
        self.line_43 = QFrame(self.groupBox_31)
        self.line_43.setObjectName(u"line_43")
        self.line_43.setGeometry(QRect(137, 10, 19, 171))
        self.line_43.setFrameShape(QFrame.VLine)
        self.line_43.setFrameShadow(QFrame.Sunken)
        self.label_446 = QLabel(self.groupBox_31)
        self.label_446.setObjectName(u"label_446")
        self.label_446.setGeometry(QRect(6, 13, 57, 16))
        self.label_446.setLayoutDirection(Qt.LeftToRight)
        self.label_446.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_448 = QLabel(self.groupBox_31)
        self.label_448.setObjectName(u"label_448")
        self.label_448.setGeometry(QRect(6, 163, 57, 16))
        self.label_448.setLayoutDirection(Qt.LeftToRight)
        self.label_448.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_449 = QLabel(self.groupBox_31)
        self.label_449.setObjectName(u"label_449")
        self.label_449.setGeometry(QRect(6, 133, 57, 16))
        self.label_449.setLayoutDirection(Qt.LeftToRight)
        self.label_449.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_450 = QLabel(self.groupBox_31)
        self.label_450.setObjectName(u"label_450")
        self.label_450.setGeometry(QRect(6, 103, 57, 16))
        self.label_450.setLayoutDirection(Qt.LeftToRight)
        self.label_450.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_453 = QLabel(self.groupBox_31)
        self.label_453.setObjectName(u"label_453")
        self.label_453.setGeometry(QRect(6, 43, 57, 16))
        self.label_453.setLayoutDirection(Qt.LeftToRight)
        self.label_453.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_455 = QLabel(self.groupBox_31)
        self.label_455.setObjectName(u"label_455")
        self.label_455.setGeometry(QRect(6, 73, 57, 16))
        self.label_455.setLayoutDirection(Qt.LeftToRight)
        self.label_455.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_tel_en = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_tel_en.setObjectName(u"doubleSpinBox_tel_en")
        self.doubleSpinBox_tel_en.setEnabled(False)
        self.doubleSpinBox_tel_en.setGeometry(QRect(404, 6, 70, 25))
        self.doubleSpinBox_tel_en.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_en.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_en.setDecimals(4)
        self.doubleSpinBox_tel_en.setMaximum(9000.000000000000000)
        self.label_456 = QLabel(self.groupBox_31)
        self.label_456.setObjectName(u"label_456")
        self.label_456.setGeometry(QRect(334, 6, 57, 16))
        self.label_456.setLayoutDirection(Qt.LeftToRight)
        self.label_456.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_tel_yuk = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_tel_yuk.setObjectName(u"doubleSpinBox_tel_yuk")
        self.doubleSpinBox_tel_yuk.setEnabled(False)
        self.doubleSpinBox_tel_yuk.setGeometry(QRect(404, 30, 70, 25))
        self.doubleSpinBox_tel_yuk.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_yuk.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_yuk.setDecimals(4)
        self.doubleSpinBox_tel_yuk.setMaximum(9000.000000000000000)
        self.label_457 = QLabel(self.groupBox_31)
        self.label_457.setObjectName(u"label_457")
        self.label_457.setGeometry(QRect(334, 30, 57, 16))
        self.label_457.setLayoutDirection(Qt.LeftToRight)
        self.label_457.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_spirkat = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_spirkat.setObjectName(u"doubleSpinBox_spirkat")
        self.doubleSpinBox_spirkat.setEnabled(False)
        self.doubleSpinBox_spirkat.setGeometry(QRect(404, 54, 70, 25))
        self.doubleSpinBox_spirkat.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_spirkat.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_spirkat.setDecimals(0)
        self.doubleSpinBox_spirkat.setMaximum(9000.000000000000000)
        self.label_458 = QLabel(self.groupBox_31)
        self.label_458.setObjectName(u"label_458")
        self.label_458.setGeometry(QRect(320, 54, 71, 20))
        self.label_458.setLayoutDirection(Qt.LeftToRight)
        self.label_458.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_kat = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_kat.setObjectName(u"doubleSpinBox_kat")
        self.doubleSpinBox_kat.setEnabled(False)
        self.doubleSpinBox_kat.setGeometry(QRect(404, 78, 70, 25))
        self.doubleSpinBox_kat.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kat.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kat.setDecimals(0)
        self.doubleSpinBox_kat.setMinimum(-9999.000000000000000)
        self.doubleSpinBox_kat.setMaximum(9000.000000000000000)
        self.label_459 = QLabel(self.groupBox_31)
        self.label_459.setObjectName(u"label_459")
        self.label_459.setGeometry(QRect(334, 78, 57, 16))
        self.label_459.setLayoutDirection(Qt.LeftToRight)
        self.label_459.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_katbosluk = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_katbosluk.setObjectName(u"doubleSpinBox_katbosluk")
        self.doubleSpinBox_katbosluk.setEnabled(False)
        self.doubleSpinBox_katbosluk.setGeometry(QRect(404, 102, 70, 25))
        self.doubleSpinBox_katbosluk.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_katbosluk.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_katbosluk.setDecimals(3)
        self.doubleSpinBox_katbosluk.setMaximum(9000.000000000000000)
        self.label_460 = QLabel(self.groupBox_31)
        self.label_460.setObjectName(u"label_460")
        self.label_460.setGeometry(QRect(320, 102, 71, 20))
        self.label_460.setLayoutDirection(Qt.LeftToRight)
        self.label_460.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_tel_uzunluk = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_tel_uzunluk.setObjectName(u"doubleSpinBox_tel_uzunluk")
        self.doubleSpinBox_tel_uzunluk.setEnabled(False)
        self.doubleSpinBox_tel_uzunluk.setGeometry(QRect(404, 126, 70, 25))
        self.doubleSpinBox_tel_uzunluk.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_uzunluk.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_uzunluk.setDecimals(3)
        self.doubleSpinBox_tel_uzunluk.setMaximum(9000.000000000000000)
        self.label_461 = QLabel(self.groupBox_31)
        self.label_461.setObjectName(u"label_461")
        self.label_461.setGeometry(QRect(300, 126, 91, 20))
        self.label_461.setLayoutDirection(Qt.LeftToRight)
        self.label_461.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_462 = QLabel(self.groupBox_31)
        self.label_462.setObjectName(u"label_462")
        self.label_462.setGeometry(QRect(310, 150, 81, 20))
        self.label_462.setLayoutDirection(Qt.LeftToRight)
        self.label_462.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_tel_agirlik = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_tel_agirlik.setObjectName(u"doubleSpinBox_tel_agirlik")
        self.doubleSpinBox_tel_agirlik.setEnabled(False)
        self.doubleSpinBox_tel_agirlik.setGeometry(QRect(404, 150, 70, 25))
        self.doubleSpinBox_tel_agirlik.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_agirlik.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_agirlik.setDecimals(3)
        self.doubleSpinBox_tel_agirlik.setMaximum(9000.000000000000000)
        self.label_463 = QLabel(self.groupBox_31)
        self.label_463.setObjectName(u"label_463")
        self.label_463.setGeometry(QRect(304, 176, 91, 20))
        self.label_463.setLayoutDirection(Qt.LeftToRight)
        self.label_463.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_sarim_yukseklik = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_sarim_yukseklik.setObjectName(u"doubleSpinBox_sarim_yukseklik")
        self.doubleSpinBox_sarim_yukseklik.setEnabled(False)
        self.doubleSpinBox_sarim_yukseklik.setGeometry(QRect(405, 174, 70, 25))
        self.doubleSpinBox_sarim_yukseklik.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_sarim_yukseklik.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sarim_yukseklik.setDecimals(3)
        self.doubleSpinBox_sarim_yukseklik.setMaximum(9000.000000000000000)
        self.label_464 = QLabel(self.groupBox_31)
        self.label_464.setObjectName(u"label_464")
        self.label_464.setGeometry(QRect(294, 200, 101, 20))
        self.label_464.setLayoutDirection(Qt.LeftToRight)
        self.label_464.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_sonkat_spir = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_sonkat_spir.setObjectName(u"doubleSpinBox_sonkat_spir")
        self.doubleSpinBox_sonkat_spir.setEnabled(False)
        self.doubleSpinBox_sonkat_spir.setGeometry(QRect(405, 198, 70, 25))
        self.doubleSpinBox_sonkat_spir.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_sonkat_spir.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_sonkat_spir.setDecimals(0)
        self.doubleSpinBox_sonkat_spir.setMaximum(9000.000000000000000)
        self.checkBox_check_spir_man = QCheckBox(self.groupBox_31)
        self.checkBox_check_spir_man.setObjectName(u"checkBox_check_spir_man")
        self.checkBox_check_spir_man.setGeometry(QRect(230, 70, 21, 22))
        self.label_kesit_error = QLabel(self.groupBox_31)
        self.label_kesit_error.setObjectName(u"label_kesit_error")
        self.label_kesit_error.setGeometry(QRect(250, 100, 21, 21))
        self.label_kesit_error.setPixmap(QPixmap(u":/staticfiles/icons/warning.png"))
        self.label_kesit_error.setScaledContents(True)
        self.label_kesit_ok = QLabel(self.groupBox_31)
        self.label_kesit_ok.setObjectName(u"label_kesit_ok")
        self.label_kesit_ok.setGeometry(QRect(230, 100, 21, 21))
        self.label_kesit_ok.setPixmap(QPixmap(u":/staticfiles/icons/checked.png"))
        self.label_kesit_ok.setScaledContents(True)
        self.label_akim_ok = QLabel(self.groupBox_31)
        self.label_akim_ok.setObjectName(u"label_akim_ok")
        self.label_akim_ok.setGeometry(QRect(230, 160, 21, 21))
        self.label_akim_ok.setPixmap(QPixmap(u":/staticfiles/icons/checked.png"))
        self.label_akim_ok.setScaledContents(True)
        self.label_akim_error = QLabel(self.groupBox_31)
        self.label_akim_error.setObjectName(u"label_akim_error")
        self.label_akim_error.setGeometry(QRect(250, 160, 21, 21))
        self.label_akim_error.setPixmap(QPixmap(u":/staticfiles/icons/warning.png"))
        self.label_akim_error.setScaledContents(True)
        self.line_48 = QFrame(self.groupBox_31)
        self.line_48.setObjectName(u"line_48")
        self.line_48.setGeometry(QRect(286, 10, 20, 211))
        self.line_48.setFrameShape(QFrame.VLine)
        self.line_48.setFrameShadow(QFrame.Sunken)
        self.tabWidget = QTabWidget(self.groupBox_31)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 200, 471, 380))
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.groupBox_gb_check_karetel_2 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_karetel_2.setObjectName(u"groupBox_gb_check_karetel_2")
        self.groupBox_gb_check_karetel_2.setGeometry(QRect(160, 81, 79, 96))
        self.groupBox_gb_check_karetel_2.setCheckable(True)
        self.groupBox_gb_check_karetel_2.setChecked(False)
        self.doubleSpinBox_karetel22 = QDoubleSpinBox(self.groupBox_gb_check_karetel_2)
        self.doubleSpinBox_karetel22.setObjectName(u"doubleSpinBox_karetel22")
        self.doubleSpinBox_karetel22.setGeometry(QRect(7, 70, 60, 25))
        font3 = QFont()
        font3.setPointSize(6)
        font3.setBold(True)
        font3.setWeight(75)
        self.doubleSpinBox_karetel22.setFont(font3)
        self.doubleSpinBox_karetel22.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel22.setAutoFillBackground(False)
        self.doubleSpinBox_karetel22.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel22.setDecimals(2)
        self.doubleSpinBox_karetel22.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel22.setSingleStep(0.100000000000000)
        self.doubleSpinBox_karetel21 = QDoubleSpinBox(self.groupBox_gb_check_karetel_2)
        self.doubleSpinBox_karetel21.setObjectName(u"doubleSpinBox_karetel21")
        self.doubleSpinBox_karetel21.setGeometry(QRect(7, 45, 60, 25))
        self.doubleSpinBox_karetel21.setFont(font3)
        self.doubleSpinBox_karetel21.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel21.setAutoFillBackground(False)
        self.doubleSpinBox_karetel21.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel21.setDecimals(2)
        self.doubleSpinBox_karetel21.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel21.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_karetel_2 = QLineEdit(self.groupBox_gb_check_karetel_2)
        self.lineEdit_mlz_karetel_2.setObjectName(u"lineEdit_mlz_karetel_2")
        self.lineEdit_mlz_karetel_2.setGeometry(QRect(7, 23, 70, 21))
        font4 = QFont()
        font4.setPointSize(5)
        font4.setBold(True)
        font4.setWeight(75)
        self.lineEdit_mlz_karetel_2.setFont(font4)
        self.groupBox_gb_check_kapton_3 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_kapton_3.setObjectName(u"groupBox_gb_check_kapton_3")
        self.groupBox_gb_check_kapton_3.setGeometry(QRect(249, 285, 80, 70))
        self.groupBox_gb_check_kapton_3.setCheckable(True)
        self.groupBox_gb_check_kapton_3.setChecked(False)
        self.lineEdit_mlz_kapton_3 = QLineEdit(self.groupBox_gb_check_kapton_3)
        self.lineEdit_mlz_kapton_3.setObjectName(u"lineEdit_mlz_kapton_3")
        self.lineEdit_mlz_kapton_3.setGeometry(QRect(0, 23, 70, 21))
        self.lineEdit_mlz_kapton_3.setFont(font4)
        self.doubleSpinBox_kapton3 = QDoubleSpinBox(self.groupBox_gb_check_kapton_3)
        self.doubleSpinBox_kapton3.setObjectName(u"doubleSpinBox_kapton3")
        self.doubleSpinBox_kapton3.setGeometry(QRect(0, 44, 60, 25))
        self.doubleSpinBox_kapton3.setFont(font3)
        self.doubleSpinBox_kapton3.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_kapton3.setAutoFillBackground(False)
        self.doubleSpinBox_kapton3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_kapton3.setDecimals(2)
        self.doubleSpinBox_kapton3.setMaximum(1000.000000000000000)
        self.doubleSpinBox_kapton3.setSingleStep(0.100000000000000)
        self.groupBox_gb_check_folyotel_1 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_folyotel_1.setObjectName(u"groupBox_gb_check_folyotel_1")
        self.groupBox_gb_check_folyotel_1.setGeometry(QRect(79, 183, 80, 95))
        self.groupBox_gb_check_folyotel_1.setCheckable(True)
        self.groupBox_gb_check_folyotel_1.setChecked(False)
        self.doubleSpinBox_folyotel12 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_1)
        self.doubleSpinBox_folyotel12.setObjectName(u"doubleSpinBox_folyotel12")
        self.doubleSpinBox_folyotel12.setGeometry(QRect(6, 69, 60, 25))
        self.doubleSpinBox_folyotel12.setFont(font3)
        self.doubleSpinBox_folyotel12.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel12.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel12.setDecimals(2)
        self.doubleSpinBox_folyotel12.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel12.setSingleStep(0.100000000000000)
        self.doubleSpinBox_folyotel11 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_1)
        self.doubleSpinBox_folyotel11.setObjectName(u"doubleSpinBox_folyotel11")
        self.doubleSpinBox_folyotel11.setGeometry(QRect(6, 45, 60, 25))
        self.doubleSpinBox_folyotel11.setFont(font3)
        self.doubleSpinBox_folyotel11.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel11.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel11.setDecimals(2)
        self.doubleSpinBox_folyotel11.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel11.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_folyotel_1 = QLineEdit(self.groupBox_gb_check_folyotel_1)
        self.lineEdit_mlz_folyotel_1.setObjectName(u"lineEdit_mlz_folyotel_1")
        self.lineEdit_mlz_folyotel_1.setGeometry(QRect(5, 23, 70, 21))
        self.lineEdit_mlz_folyotel_1.setFont(font4)
        self.label_454 = QLabel(self.tab_1)
        self.label_454.setObjectName(u"label_454")
        self.label_454.setGeometry(QRect(11, 104, 57, 16))
        self.label_454.setLayoutDirection(Qt.LeftToRight)
        self.label_454.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_452 = QLabel(self.tab_1)
        self.label_452.setObjectName(u"label_452")
        self.label_452.setGeometry(QRect(11, 24, 61, 31))
        self.label_452.setLayoutDirection(Qt.LeftToRight)
        self.label_452.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_29 = QFrame(self.tab_1)
        self.line_29.setObjectName(u"line_29")
        self.line_29.setGeometry(QRect(-4, -7, 471, 16))
        self.line_29.setFrameShape(QFrame.HLine)
        self.line_29.setFrameShadow(QFrame.Sunken)
        self.line_28 = QFrame(self.tab_1)
        self.line_28.setObjectName(u"line_28")
        self.line_28.setGeometry(QRect(-4, 71, 471, 16))
        self.line_28.setFrameShape(QFrame.HLine)
        self.line_28.setFrameShadow(QFrame.Sunken)
        self.line_33 = QFrame(self.tab_1)
        self.line_33.setObjectName(u"line_33")
        self.line_33.setGeometry(QRect(-4, 173, 471, 16))
        self.line_33.setFrameShape(QFrame.HLine)
        self.line_33.setFrameShadow(QFrame.Sunken)
        self.groupBox_gb_check_folyotel_2 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_folyotel_2.setObjectName(u"groupBox_gb_check_folyotel_2")
        self.groupBox_gb_check_folyotel_2.setGeometry(QRect(161, 184, 80, 94))
        self.groupBox_gb_check_folyotel_2.setCheckable(True)
        self.groupBox_gb_check_folyotel_2.setChecked(False)
        self.doubleSpinBox_folyotel22 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_2)
        self.doubleSpinBox_folyotel22.setObjectName(u"doubleSpinBox_folyotel22")
        self.doubleSpinBox_folyotel22.setGeometry(QRect(7, 70, 60, 25))
        self.doubleSpinBox_folyotel22.setFont(font3)
        self.doubleSpinBox_folyotel22.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel22.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel22.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel22.setDecimals(2)
        self.doubleSpinBox_folyotel22.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel22.setSingleStep(0.100000000000000)
        self.doubleSpinBox_folyotel21 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_2)
        self.doubleSpinBox_folyotel21.setObjectName(u"doubleSpinBox_folyotel21")
        self.doubleSpinBox_folyotel21.setGeometry(QRect(7, 46, 60, 25))
        self.doubleSpinBox_folyotel21.setFont(font3)
        self.doubleSpinBox_folyotel21.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel21.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel21.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel21.setDecimals(2)
        self.doubleSpinBox_folyotel21.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel21.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_folyotel_2 = QLineEdit(self.groupBox_gb_check_folyotel_2)
        self.lineEdit_mlz_folyotel_2.setObjectName(u"lineEdit_mlz_folyotel_2")
        self.lineEdit_mlz_folyotel_2.setGeometry(QRect(7, 23, 70, 21))
        self.lineEdit_mlz_folyotel_2.setFont(font4)
        self.line_38 = QFrame(self.tab_1)
        self.line_38.setObjectName(u"line_38")
        self.line_38.setGeometry(QRect(-4, 274, 471, 16))
        self.line_38.setFrameShape(QFrame.HLine)
        self.line_38.setFrameShadow(QFrame.Sunken)
        self.groupBox_gb_check_karetel_3 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_karetel_3.setObjectName(u"groupBox_gb_check_karetel_3")
        self.groupBox_gb_check_karetel_3.setGeometry(QRect(242, 81, 79, 96))
        self.groupBox_gb_check_karetel_3.setCheckable(True)
        self.groupBox_gb_check_karetel_3.setChecked(False)
        self.doubleSpinBox_karetel32 = QDoubleSpinBox(self.groupBox_gb_check_karetel_3)
        self.doubleSpinBox_karetel32.setObjectName(u"doubleSpinBox_karetel32")
        self.doubleSpinBox_karetel32.setGeometry(QRect(6, 70, 60, 25))
        self.doubleSpinBox_karetel32.setFont(font3)
        self.doubleSpinBox_karetel32.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel32.setAutoFillBackground(False)
        self.doubleSpinBox_karetel32.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel32.setDecimals(2)
        self.doubleSpinBox_karetel32.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel32.setSingleStep(0.100000000000000)
        self.doubleSpinBox_karetel31 = QDoubleSpinBox(self.groupBox_gb_check_karetel_3)
        self.doubleSpinBox_karetel31.setObjectName(u"doubleSpinBox_karetel31")
        self.doubleSpinBox_karetel31.setGeometry(QRect(6, 45, 60, 25))
        self.doubleSpinBox_karetel31.setFont(font3)
        self.doubleSpinBox_karetel31.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel31.setAutoFillBackground(False)
        self.doubleSpinBox_karetel31.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel31.setDecimals(2)
        self.doubleSpinBox_karetel31.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel31.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_karetel_3 = QLineEdit(self.groupBox_gb_check_karetel_3)
        self.lineEdit_mlz_karetel_3.setObjectName(u"lineEdit_mlz_karetel_3")
        self.lineEdit_mlz_karetel_3.setGeometry(QRect(7, 23, 70, 21))
        self.lineEdit_mlz_karetel_3.setFont(font4)
        self.groupBox_gb_check_folyotel_4 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_folyotel_4.setObjectName(u"groupBox_gb_check_folyotel_4")
        self.groupBox_gb_check_folyotel_4.setGeometry(QRect(324, 185, 80, 94))
        self.groupBox_gb_check_folyotel_4.setCheckable(True)
        self.groupBox_gb_check_folyotel_4.setChecked(False)
        self.doubleSpinBox_folyotel42 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_4)
        self.doubleSpinBox_folyotel42.setObjectName(u"doubleSpinBox_folyotel42")
        self.doubleSpinBox_folyotel42.setGeometry(QRect(5, 68, 60, 25))
        self.doubleSpinBox_folyotel42.setFont(font3)
        self.doubleSpinBox_folyotel42.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel42.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel42.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel42.setDecimals(2)
        self.doubleSpinBox_folyotel42.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel42.setSingleStep(0.100000000000000)
        self.doubleSpinBox_folyotel41 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_4)
        self.doubleSpinBox_folyotel41.setObjectName(u"doubleSpinBox_folyotel41")
        self.doubleSpinBox_folyotel41.setGeometry(QRect(5, 43, 60, 25))
        self.doubleSpinBox_folyotel41.setFont(font3)
        self.doubleSpinBox_folyotel41.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel41.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel41.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel41.setDecimals(2)
        self.doubleSpinBox_folyotel41.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel41.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_folyotel_4 = QLineEdit(self.groupBox_gb_check_folyotel_4)
        self.lineEdit_mlz_folyotel_4.setObjectName(u"lineEdit_mlz_folyotel_4")
        self.lineEdit_mlz_folyotel_4.setGeometry(QRect(5, 20, 70, 21))
        self.lineEdit_mlz_folyotel_4.setFont(font4)
        self.groupBox_gb_check_tel_3 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_tel_3.setObjectName(u"groupBox_gb_check_tel_3")
        self.groupBox_gb_check_tel_3.setGeometry(QRect(241, 4, 78, 73))
        self.groupBox_gb_check_tel_3.setCheckable(True)
        self.groupBox_gb_check_tel_3.setChecked(False)
        self.lineEdit_mlz_tel_3 = QLineEdit(self.groupBox_gb_check_tel_3)
        self.lineEdit_mlz_tel_3.setObjectName(u"lineEdit_mlz_tel_3")
        self.lineEdit_mlz_tel_3.setGeometry(QRect(0, 23, 70, 21))
        self.lineEdit_mlz_tel_3.setFont(font4)
        self.doubleSpinBox_mancap_3 = QDoubleSpinBox(self.groupBox_gb_check_tel_3)
        self.doubleSpinBox_mancap_3.setObjectName(u"doubleSpinBox_mancap_3")
        self.doubleSpinBox_mancap_3.setGeometry(QRect(0, 46, 60, 25))
        self.doubleSpinBox_mancap_3.setFont(font3)
        self.doubleSpinBox_mancap_3.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_mancap_3.setAutoFillBackground(False)
        self.doubleSpinBox_mancap_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_mancap_3.setDecimals(2)
        self.doubleSpinBox_mancap_3.setMaximum(1000.000000000000000)
        self.doubleSpinBox_mancap_3.setSingleStep(0.100000000000000)
        self.groupBox_gb_check_tel_2 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_tel_2.setObjectName(u"groupBox_gb_check_tel_2")
        self.groupBox_gb_check_tel_2.setGeometry(QRect(161, 4, 78, 73))
        self.groupBox_gb_check_tel_2.setCheckable(True)
        self.groupBox_gb_check_tel_2.setChecked(False)
        self.doubleSpinBox_mancap_2 = QDoubleSpinBox(self.groupBox_gb_check_tel_2)
        self.doubleSpinBox_mancap_2.setObjectName(u"doubleSpinBox_mancap_2")
        self.doubleSpinBox_mancap_2.setGeometry(QRect(0, 46, 60, 25))
        self.doubleSpinBox_mancap_2.setFont(font3)
        self.doubleSpinBox_mancap_2.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_mancap_2.setAutoFillBackground(False)
        self.doubleSpinBox_mancap_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_mancap_2.setDecimals(2)
        self.doubleSpinBox_mancap_2.setMaximum(1000.000000000000000)
        self.doubleSpinBox_mancap_2.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_tel_2 = QLineEdit(self.groupBox_gb_check_tel_2)
        self.lineEdit_mlz_tel_2.setObjectName(u"lineEdit_mlz_tel_2")
        self.lineEdit_mlz_tel_2.setGeometry(QRect(0, 23, 70, 21))
        self.lineEdit_mlz_tel_2.setFont(font4)
        self.label_447 = QLabel(self.tab_1)
        self.label_447.setObjectName(u"label_447")
        self.label_447.setGeometry(QRect(11, 204, 57, 16))
        self.label_447.setLayoutDirection(Qt.LeftToRight)
        self.label_447.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_gb_check_tel_4 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_tel_4.setObjectName(u"groupBox_gb_check_tel_4")
        self.groupBox_gb_check_tel_4.setGeometry(QRect(326, 4, 78, 73))
        self.groupBox_gb_check_tel_4.setCheckable(True)
        self.groupBox_gb_check_tel_4.setChecked(False)
        self.lineEdit_mlz_tel_4 = QLineEdit(self.groupBox_gb_check_tel_4)
        self.lineEdit_mlz_tel_4.setObjectName(u"lineEdit_mlz_tel_4")
        self.lineEdit_mlz_tel_4.setGeometry(QRect(2, 24, 70, 21))
        self.lineEdit_mlz_tel_4.setFont(font4)
        self.doubleSpinBox_mancap_4 = QDoubleSpinBox(self.groupBox_gb_check_tel_4)
        self.doubleSpinBox_mancap_4.setObjectName(u"doubleSpinBox_mancap_4")
        self.doubleSpinBox_mancap_4.setGeometry(QRect(2, 47, 60, 25))
        self.doubleSpinBox_mancap_4.setFont(font3)
        self.doubleSpinBox_mancap_4.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_mancap_4.setAutoFillBackground(False)
        self.doubleSpinBox_mancap_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_mancap_4.setDecimals(2)
        self.doubleSpinBox_mancap_4.setMaximum(1000.000000000000000)
        self.doubleSpinBox_mancap_4.setSingleStep(0.100000000000000)
        self.label_451 = QLabel(self.tab_1)
        self.label_451.setObjectName(u"label_451")
        self.label_451.setGeometry(QRect(11, 304, 57, 16))
        self.label_451.setLayoutDirection(Qt.LeftToRight)
        self.label_451.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_gb_check_karetel_4 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_karetel_4.setObjectName(u"groupBox_gb_check_karetel_4")
        self.groupBox_gb_check_karetel_4.setGeometry(QRect(325, 81, 79, 96))
        self.groupBox_gb_check_karetel_4.setCheckable(True)
        self.groupBox_gb_check_karetel_4.setChecked(False)
        self.doubleSpinBox_karetel42 = QDoubleSpinBox(self.groupBox_gb_check_karetel_4)
        self.doubleSpinBox_karetel42.setObjectName(u"doubleSpinBox_karetel42")
        self.doubleSpinBox_karetel42.setGeometry(QRect(6, 70, 60, 25))
        self.doubleSpinBox_karetel42.setFont(font3)
        self.doubleSpinBox_karetel42.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel42.setAutoFillBackground(False)
        self.doubleSpinBox_karetel42.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel42.setDecimals(2)
        self.doubleSpinBox_karetel42.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel42.setSingleStep(0.100000000000000)
        self.doubleSpinBox_karetel41 = QDoubleSpinBox(self.groupBox_gb_check_karetel_4)
        self.doubleSpinBox_karetel41.setObjectName(u"doubleSpinBox_karetel41")
        self.doubleSpinBox_karetel41.setGeometry(QRect(6, 45, 60, 25))
        self.doubleSpinBox_karetel41.setFont(font3)
        self.doubleSpinBox_karetel41.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel41.setAutoFillBackground(False)
        self.doubleSpinBox_karetel41.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel41.setDecimals(2)
        self.doubleSpinBox_karetel41.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel41.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_karetel_4 = QLineEdit(self.groupBox_gb_check_karetel_4)
        self.lineEdit_mlz_karetel_4.setObjectName(u"lineEdit_mlz_karetel_4")
        self.lineEdit_mlz_karetel_4.setGeometry(QRect(7, 23, 70, 21))
        self.lineEdit_mlz_karetel_4.setFont(font4)
        self.groupBox_gb_check_kapton_2 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_kapton_2.setObjectName(u"groupBox_gb_check_kapton_2")
        self.groupBox_gb_check_kapton_2.setGeometry(QRect(165, 285, 80, 70))
        self.groupBox_gb_check_kapton_2.setCheckable(True)
        self.groupBox_gb_check_kapton_2.setChecked(False)
        self.lineEdit_mlz_kapton_2 = QLineEdit(self.groupBox_gb_check_kapton_2)
        self.lineEdit_mlz_kapton_2.setObjectName(u"lineEdit_mlz_kapton_2")
        self.lineEdit_mlz_kapton_2.setGeometry(QRect(0, 23, 70, 21))
        self.lineEdit_mlz_kapton_2.setFont(font4)
        self.doubleSpinBox_kapton2 = QDoubleSpinBox(self.groupBox_gb_check_kapton_2)
        self.doubleSpinBox_kapton2.setObjectName(u"doubleSpinBox_kapton2")
        self.doubleSpinBox_kapton2.setGeometry(QRect(0, 44, 60, 25))
        self.doubleSpinBox_kapton2.setFont(font3)
        self.doubleSpinBox_kapton2.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_kapton2.setAutoFillBackground(False)
        self.doubleSpinBox_kapton2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_kapton2.setDecimals(2)
        self.doubleSpinBox_kapton2.setMaximum(1000.000000000000000)
        self.doubleSpinBox_kapton2.setSingleStep(0.100000000000000)
        self.groupBox_gb_check_folyotel_3 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_folyotel_3.setObjectName(u"groupBox_gb_check_folyotel_3")
        self.groupBox_gb_check_folyotel_3.setGeometry(QRect(244, 185, 80, 94))
        self.groupBox_gb_check_folyotel_3.setCheckable(True)
        self.groupBox_gb_check_folyotel_3.setChecked(False)
        self.doubleSpinBox_folyotel32 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_3)
        self.doubleSpinBox_folyotel32.setObjectName(u"doubleSpinBox_folyotel32")
        self.doubleSpinBox_folyotel32.setGeometry(QRect(6, 68, 60, 25))
        self.doubleSpinBox_folyotel32.setFont(font3)
        self.doubleSpinBox_folyotel32.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel32.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel32.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel32.setDecimals(2)
        self.doubleSpinBox_folyotel32.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel32.setSingleStep(0.100000000000000)
        self.doubleSpinBox_folyotel31 = QDoubleSpinBox(self.groupBox_gb_check_folyotel_3)
        self.doubleSpinBox_folyotel31.setObjectName(u"doubleSpinBox_folyotel31")
        self.doubleSpinBox_folyotel31.setGeometry(QRect(6, 44, 60, 25))
        self.doubleSpinBox_folyotel31.setFont(font3)
        self.doubleSpinBox_folyotel31.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_folyotel31.setAutoFillBackground(False)
        self.doubleSpinBox_folyotel31.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_folyotel31.setDecimals(2)
        self.doubleSpinBox_folyotel31.setMaximum(1000.000000000000000)
        self.doubleSpinBox_folyotel31.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_folyotel_3 = QLineEdit(self.groupBox_gb_check_folyotel_3)
        self.lineEdit_mlz_folyotel_3.setObjectName(u"lineEdit_mlz_folyotel_3")
        self.lineEdit_mlz_folyotel_3.setGeometry(QRect(6, 21, 70, 21))
        self.lineEdit_mlz_folyotel_3.setFont(font4)
        self.groupBox_gb_check_kapton_1 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_kapton_1.setObjectName(u"groupBox_gb_check_kapton_1")
        self.groupBox_gb_check_kapton_1.setGeometry(QRect(79, 285, 80, 70))
        self.groupBox_gb_check_kapton_1.setCheckable(True)
        self.groupBox_gb_check_kapton_1.setChecked(False)
        self.doubleSpinBox_kapton1 = QDoubleSpinBox(self.groupBox_gb_check_kapton_1)
        self.doubleSpinBox_kapton1.setObjectName(u"doubleSpinBox_kapton1")
        self.doubleSpinBox_kapton1.setGeometry(QRect(0, 44, 60, 25))
        self.doubleSpinBox_kapton1.setFont(font3)
        self.doubleSpinBox_kapton1.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_kapton1.setAutoFillBackground(False)
        self.doubleSpinBox_kapton1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_kapton1.setDecimals(2)
        self.doubleSpinBox_kapton1.setMaximum(1000.000000000000000)
        self.doubleSpinBox_kapton1.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_kapton_1 = QLineEdit(self.groupBox_gb_check_kapton_1)
        self.lineEdit_mlz_kapton_1.setObjectName(u"lineEdit_mlz_kapton_1")
        self.lineEdit_mlz_kapton_1.setGeometry(QRect(0, 23, 70, 21))
        self.lineEdit_mlz_kapton_1.setFont(font4)
        self.groupBox_gb_check_kapton_4 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_kapton_4.setObjectName(u"groupBox_gb_check_kapton_4")
        self.groupBox_gb_check_kapton_4.setGeometry(QRect(329, 285, 80, 70))
        self.groupBox_gb_check_kapton_4.setCheckable(True)
        self.groupBox_gb_check_kapton_4.setChecked(False)
        self.lineEdit_mlz_kapton_4 = QLineEdit(self.groupBox_gb_check_kapton_4)
        self.lineEdit_mlz_kapton_4.setObjectName(u"lineEdit_mlz_kapton_4")
        self.lineEdit_mlz_kapton_4.setGeometry(QRect(0, 23, 70, 21))
        self.lineEdit_mlz_kapton_4.setFont(font4)
        self.doubleSpinBox_kapton4 = QDoubleSpinBox(self.groupBox_gb_check_kapton_4)
        self.doubleSpinBox_kapton4.setObjectName(u"doubleSpinBox_kapton4")
        self.doubleSpinBox_kapton4.setGeometry(QRect(0, 44, 60, 25))
        self.doubleSpinBox_kapton4.setFont(font3)
        self.doubleSpinBox_kapton4.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_kapton4.setAutoFillBackground(False)
        self.doubleSpinBox_kapton4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_kapton4.setDecimals(2)
        self.doubleSpinBox_kapton4.setMaximum(1000.000000000000000)
        self.doubleSpinBox_kapton4.setSingleStep(0.100000000000000)
        self.groupBox_gb_check_tel_1 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_tel_1.setObjectName(u"groupBox_gb_check_tel_1")
        self.groupBox_gb_check_tel_1.setGeometry(QRect(81, 4, 78, 73))
        self.groupBox_gb_check_tel_1.setFlat(False)
        self.groupBox_gb_check_tel_1.setCheckable(True)
        self.groupBox_gb_check_tel_1.setChecked(False)
        self.lineEdit_mlz_tel_1 = QLineEdit(self.groupBox_gb_check_tel_1)
        self.lineEdit_mlz_tel_1.setObjectName(u"lineEdit_mlz_tel_1")
        self.lineEdit_mlz_tel_1.setGeometry(QRect(4, 23, 70, 21))
        self.lineEdit_mlz_tel_1.setFont(font4)
        self.doubleSpinBox_mancap_1 = QDoubleSpinBox(self.groupBox_gb_check_tel_1)
        self.doubleSpinBox_mancap_1.setObjectName(u"doubleSpinBox_mancap_1")
        self.doubleSpinBox_mancap_1.setGeometry(QRect(4, 46, 60, 25))
        self.doubleSpinBox_mancap_1.setFont(font3)
        self.doubleSpinBox_mancap_1.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_mancap_1.setAutoFillBackground(False)
        self.doubleSpinBox_mancap_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_mancap_1.setDecimals(2)
        self.doubleSpinBox_mancap_1.setMaximum(1000.000000000000000)
        self.doubleSpinBox_mancap_1.setSingleStep(0.100000000000000)
        self.groupBox_gb_check_karetel_1 = QGroupBox(self.tab_1)
        self.groupBox_gb_check_karetel_1.setObjectName(u"groupBox_gb_check_karetel_1")
        self.groupBox_gb_check_karetel_1.setGeometry(QRect(76, 81, 80, 96))
        self.groupBox_gb_check_karetel_1.setCheckable(True)
        self.groupBox_gb_check_karetel_1.setChecked(False)
        self.doubleSpinBox_karetel12 = QDoubleSpinBox(self.groupBox_gb_check_karetel_1)
        self.doubleSpinBox_karetel12.setObjectName(u"doubleSpinBox_karetel12")
        self.doubleSpinBox_karetel12.setGeometry(QRect(6, 70, 60, 25))
        self.doubleSpinBox_karetel12.setFont(font3)
        self.doubleSpinBox_karetel12.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel12.setAutoFillBackground(False)
        self.doubleSpinBox_karetel12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel12.setDecimals(2)
        self.doubleSpinBox_karetel12.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel12.setSingleStep(0.100000000000000)
        self.doubleSpinBox_karetel11 = QDoubleSpinBox(self.groupBox_gb_check_karetel_1)
        self.doubleSpinBox_karetel11.setObjectName(u"doubleSpinBox_karetel11")
        self.doubleSpinBox_karetel11.setGeometry(QRect(6, 45, 60, 25))
        self.doubleSpinBox_karetel11.setFont(font3)
        self.doubleSpinBox_karetel11.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_karetel11.setAutoFillBackground(False)
        self.doubleSpinBox_karetel11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_karetel11.setDecimals(2)
        self.doubleSpinBox_karetel11.setMaximum(1000.000000000000000)
        self.doubleSpinBox_karetel11.setSingleStep(0.100000000000000)
        self.lineEdit_mlz_karetel_1 = QLineEdit(self.groupBox_gb_check_karetel_1)
        self.lineEdit_mlz_karetel_1.setObjectName(u"lineEdit_mlz_karetel_1")
        self.lineEdit_mlz_karetel_1.setGeometry(QRect(7, 23, 70, 21))
        self.lineEdit_mlz_karetel_1.setFont(font4)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.line_31 = QFrame(self.tab_2)
        self.line_31.setObjectName(u"line_31")
        self.line_31.setGeometry(QRect(0, 71, 471, 16))
        self.line_31.setFrameShape(QFrame.HLine)
        self.line_31.setFrameShadow(QFrame.Sunken)
        self.label_466 = QLabel(self.tab_2)
        self.label_466.setObjectName(u"label_466")
        self.label_466.setGeometry(QRect(15, 104, 57, 16))
        self.label_466.setLayoutDirection(Qt.LeftToRight)
        self.label_466.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_39 = QFrame(self.tab_2)
        self.line_39.setObjectName(u"line_39")
        self.line_39.setGeometry(QRect(0, 274, 471, 16))
        self.line_39.setFrameShape(QFrame.HLine)
        self.line_39.setFrameShadow(QFrame.Sunken)
        self.label_465 = QLabel(self.tab_2)
        self.label_465.setObjectName(u"label_465")
        self.label_465.setGeometry(QRect(15, 24, 61, 31))
        self.label_465.setLayoutDirection(Qt.LeftToRight)
        self.label_465.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_468 = QLabel(self.tab_2)
        self.label_468.setObjectName(u"label_468")
        self.label_468.setGeometry(QRect(15, 304, 57, 16))
        self.label_468.setLayoutDirection(Qt.LeftToRight)
        self.label_468.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_467 = QLabel(self.tab_2)
        self.label_467.setObjectName(u"label_467")
        self.label_467.setGeometry(QRect(15, 204, 57, 16))
        self.label_467.setLayoutDirection(Qt.LeftToRight)
        self.label_467.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_34 = QFrame(self.tab_2)
        self.line_34.setObjectName(u"line_34")
        self.line_34.setGeometry(QRect(0, 173, 471, 16))
        self.line_34.setFrameShape(QFrame.HLine)
        self.line_34.setFrameShadow(QFrame.Sunken)
        self.line_30 = QFrame(self.tab_2)
        self.line_30.setObjectName(u"line_30")
        self.line_30.setGeometry(QRect(0, -7, 471, 16))
        self.line_30.setFrameShape(QFrame.HLine)
        self.line_30.setFrameShadow(QFrame.Sunken)
        self.doubleSpinBox_tel_agirlik_1 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_tel_agirlik_1.setObjectName(u"doubleSpinBox_tel_agirlik_1")
        self.doubleSpinBox_tel_agirlik_1.setEnabled(False)
        self.doubleSpinBox_tel_agirlik_1.setGeometry(QRect(86, 20, 70, 25))
        self.doubleSpinBox_tel_agirlik_1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_agirlik_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_agirlik_1.setDecimals(3)
        self.doubleSpinBox_tel_agirlik_1.setMaximum(9000.000000000000000)
        self.doubleSpinBox_tel_agirlik_2 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_tel_agirlik_2.setObjectName(u"doubleSpinBox_tel_agirlik_2")
        self.doubleSpinBox_tel_agirlik_2.setEnabled(False)
        self.doubleSpinBox_tel_agirlik_2.setGeometry(QRect(176, 20, 70, 25))
        self.doubleSpinBox_tel_agirlik_2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_agirlik_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_agirlik_2.setDecimals(3)
        self.doubleSpinBox_tel_agirlik_2.setMaximum(9000.000000000000000)
        self.doubleSpinBox_tel_agirlik_3 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_tel_agirlik_3.setObjectName(u"doubleSpinBox_tel_agirlik_3")
        self.doubleSpinBox_tel_agirlik_3.setEnabled(False)
        self.doubleSpinBox_tel_agirlik_3.setGeometry(QRect(270, 20, 70, 25))
        self.doubleSpinBox_tel_agirlik_3.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_agirlik_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_agirlik_3.setDecimals(3)
        self.doubleSpinBox_tel_agirlik_3.setMaximum(9000.000000000000000)
        self.doubleSpinBox_tel_agirlik_4 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_tel_agirlik_4.setObjectName(u"doubleSpinBox_tel_agirlik_4")
        self.doubleSpinBox_tel_agirlik_4.setEnabled(False)
        self.doubleSpinBox_tel_agirlik_4.setGeometry(QRect(368, 20, 70, 25))
        self.doubleSpinBox_tel_agirlik_4.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_tel_agirlik_4.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_tel_agirlik_4.setDecimals(3)
        self.doubleSpinBox_tel_agirlik_4.setMaximum(9000.000000000000000)
        self.doubleSpinBox_karetel_agirlik_1 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_karetel_agirlik_1.setObjectName(u"doubleSpinBox_karetel_agirlik_1")
        self.doubleSpinBox_karetel_agirlik_1.setEnabled(False)
        self.doubleSpinBox_karetel_agirlik_1.setGeometry(QRect(86, 100, 70, 25))
        self.doubleSpinBox_karetel_agirlik_1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_karetel_agirlik_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_karetel_agirlik_1.setDecimals(3)
        self.doubleSpinBox_karetel_agirlik_1.setMaximum(9000.000000000000000)
        self.line = QFrame(self.tab_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(153, 20, 20, 331))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.tab_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(250, 20, 20, 331))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.tab_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(340, 20, 20, 331))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.tab_2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(70, 1, 20, 353))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.doubleSpinBox_karetel_agirlik_2 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_karetel_agirlik_2.setObjectName(u"doubleSpinBox_karetel_agirlik_2")
        self.doubleSpinBox_karetel_agirlik_2.setEnabled(False)
        self.doubleSpinBox_karetel_agirlik_2.setGeometry(QRect(176, 100, 70, 25))
        self.doubleSpinBox_karetel_agirlik_2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_karetel_agirlik_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_karetel_agirlik_2.setDecimals(3)
        self.doubleSpinBox_karetel_agirlik_2.setMaximum(9000.000000000000000)
        self.doubleSpinBox_karetel_agirlik_3 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_karetel_agirlik_3.setObjectName(u"doubleSpinBox_karetel_agirlik_3")
        self.doubleSpinBox_karetel_agirlik_3.setEnabled(False)
        self.doubleSpinBox_karetel_agirlik_3.setGeometry(QRect(270, 100, 70, 25))
        self.doubleSpinBox_karetel_agirlik_3.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_karetel_agirlik_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_karetel_agirlik_3.setDecimals(3)
        self.doubleSpinBox_karetel_agirlik_3.setMaximum(9000.000000000000000)
        self.doubleSpinBox_karetel_agirlik_4 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_karetel_agirlik_4.setObjectName(u"doubleSpinBox_karetel_agirlik_4")
        self.doubleSpinBox_karetel_agirlik_4.setEnabled(False)
        self.doubleSpinBox_karetel_agirlik_4.setGeometry(QRect(368, 100, 70, 25))
        self.doubleSpinBox_karetel_agirlik_4.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_karetel_agirlik_4.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_karetel_agirlik_4.setDecimals(3)
        self.doubleSpinBox_karetel_agirlik_4.setMaximum(9000.000000000000000)
        self.doubleSpinBox_folyo_agirlik_1 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_folyo_agirlik_1.setObjectName(u"doubleSpinBox_folyo_agirlik_1")
        self.doubleSpinBox_folyo_agirlik_1.setEnabled(False)
        self.doubleSpinBox_folyo_agirlik_1.setGeometry(QRect(86, 200, 70, 25))
        self.doubleSpinBox_folyo_agirlik_1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_folyo_agirlik_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_folyo_agirlik_1.setDecimals(3)
        self.doubleSpinBox_folyo_agirlik_1.setMaximum(9000.000000000000000)
        self.doubleSpinBox_folyo_agirlik_2 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_folyo_agirlik_2.setObjectName(u"doubleSpinBox_folyo_agirlik_2")
        self.doubleSpinBox_folyo_agirlik_2.setEnabled(False)
        self.doubleSpinBox_folyo_agirlik_2.setGeometry(QRect(176, 200, 70, 25))
        self.doubleSpinBox_folyo_agirlik_2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_folyo_agirlik_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_folyo_agirlik_2.setDecimals(3)
        self.doubleSpinBox_folyo_agirlik_2.setMaximum(9000.000000000000000)
        self.doubleSpinBox_folyo_agirlik_3 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_folyo_agirlik_3.setObjectName(u"doubleSpinBox_folyo_agirlik_3")
        self.doubleSpinBox_folyo_agirlik_3.setEnabled(False)
        self.doubleSpinBox_folyo_agirlik_3.setGeometry(QRect(270, 200, 70, 25))
        self.doubleSpinBox_folyo_agirlik_3.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_folyo_agirlik_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_folyo_agirlik_3.setDecimals(3)
        self.doubleSpinBox_folyo_agirlik_3.setMaximum(9000.000000000000000)
        self.doubleSpinBox_folyo_agirlik_4 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_folyo_agirlik_4.setObjectName(u"doubleSpinBox_folyo_agirlik_4")
        self.doubleSpinBox_folyo_agirlik_4.setEnabled(False)
        self.doubleSpinBox_folyo_agirlik_4.setGeometry(QRect(368, 200, 70, 25))
        self.doubleSpinBox_folyo_agirlik_4.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_folyo_agirlik_4.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_folyo_agirlik_4.setDecimals(3)
        self.doubleSpinBox_folyo_agirlik_4.setMaximum(9000.000000000000000)
        self.doubleSpinBox_kapton_agirlik_1 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_kapton_agirlik_1.setObjectName(u"doubleSpinBox_kapton_agirlik_1")
        self.doubleSpinBox_kapton_agirlik_1.setEnabled(False)
        self.doubleSpinBox_kapton_agirlik_1.setGeometry(QRect(86, 300, 70, 25))
        self.doubleSpinBox_kapton_agirlik_1.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kapton_agirlik_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kapton_agirlik_1.setDecimals(3)
        self.doubleSpinBox_kapton_agirlik_1.setMaximum(9000.000000000000000)
        self.doubleSpinBox_kapton_agirlik_2 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_kapton_agirlik_2.setObjectName(u"doubleSpinBox_kapton_agirlik_2")
        self.doubleSpinBox_kapton_agirlik_2.setEnabled(False)
        self.doubleSpinBox_kapton_agirlik_2.setGeometry(QRect(176, 300, 70, 25))
        self.doubleSpinBox_kapton_agirlik_2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kapton_agirlik_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kapton_agirlik_2.setDecimals(3)
        self.doubleSpinBox_kapton_agirlik_2.setMaximum(9000.000000000000000)
        self.doubleSpinBox_kapton_agirlik_3 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_kapton_agirlik_3.setObjectName(u"doubleSpinBox_kapton_agirlik_3")
        self.doubleSpinBox_kapton_agirlik_3.setEnabled(False)
        self.doubleSpinBox_kapton_agirlik_3.setGeometry(QRect(270, 300, 70, 25))
        self.doubleSpinBox_kapton_agirlik_3.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kapton_agirlik_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kapton_agirlik_3.setDecimals(3)
        self.doubleSpinBox_kapton_agirlik_3.setMaximum(9000.000000000000000)
        self.doubleSpinBox_kapton_agirlik_4 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_kapton_agirlik_4.setObjectName(u"doubleSpinBox_kapton_agirlik_4")
        self.doubleSpinBox_kapton_agirlik_4.setEnabled(False)
        self.doubleSpinBox_kapton_agirlik_4.setGeometry(QRect(368, 300, 70, 25))
        self.doubleSpinBox_kapton_agirlik_4.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kapton_agirlik_4.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kapton_agirlik_4.setDecimals(3)
        self.doubleSpinBox_kapton_agirlik_4.setMaximum(9000.000000000000000)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_469 = QLabel(self.groupBox_31)
        self.label_469.setObjectName(u"label_469")
        self.label_469.setGeometry(QRect(150, 13, 57, 16))
        self.label_469.setLayoutDirection(Qt.LeftToRight)
        self.label_469.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_gauss = QDoubleSpinBox(self.groupBox_31)
        self.doubleSpinBox_gauss.setObjectName(u"doubleSpinBox_gauss")
        self.doubleSpinBox_gauss.setEnabled(True)
        self.doubleSpinBox_gauss.setGeometry(QRect(209, 10, 81, 25))
        self.doubleSpinBox_gauss.setBaseSize(QSize(0, 5))
        self.doubleSpinBox_gauss.setFont(font1)
        self.doubleSpinBox_gauss.setLayoutDirection(Qt.LeftToRight)
        self.doubleSpinBox_gauss.setAutoFillBackground(False)
        self.doubleSpinBox_gauss.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox_gauss.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_gauss.setDecimals(0)
        self.doubleSpinBox_gauss.setMaximum(9999999.000000000000000)
        self.doubleSpinBox_gauss.setSingleStep(250.000000000000000)
        self.lineEdit_kademeadi = QLineEdit(self.frame_2)
        self.lineEdit_kademeadi.setObjectName(u"lineEdit_kademeadi")
        self.lineEdit_kademeadi.setEnabled(False)
        self.lineEdit_kademeadi.setGeometry(QRect(59, 38, 441, 20))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 128))
        brush1.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush1)
#endif
        self.lineEdit_kademeadi.setPalette(palette)
        self.lineEdit_kademeadi.setFont(font)
        self.lineEdit_kademeadi.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_kademe_no = QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_kademe_no.setObjectName(u"doubleSpinBox_kademe_no")
        self.doubleSpinBox_kademe_no.setEnabled(False)
        self.doubleSpinBox_kademe_no.setGeometry(QRect(24, 36, 31, 23))
        self.doubleSpinBox_kademe_no.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_kademe_no.setDecimals(0)
        self.doubleSpinBox_kademe_no.setMaximum(10.000000000000000)
        self.pushButton_kad_1 = QPushButton(self.frame_2)
        self.pushButton_kad_1.setObjectName(u"pushButton_kad_1")
        self.pushButton_kad_1.setGeometry(QRect(10, 10, 47, 25))
        self.pushButton_kad_1.setMinimumSize(QSize(47, 0))
        self.pushButton_kad_2 = QPushButton(self.frame_2)
        self.pushButton_kad_2.setObjectName(u"pushButton_kad_2")
        self.pushButton_kad_2.setGeometry(QRect(60, 10, 47, 25))
        self.pushButton_kad_2.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_3 = QPushButton(self.frame_2)
        self.pushButton_kad_3.setObjectName(u"pushButton_kad_3")
        self.pushButton_kad_3.setGeometry(QRect(110, 10, 47, 25))
        self.pushButton_kad_3.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_4 = QPushButton(self.frame_2)
        self.pushButton_kad_4.setObjectName(u"pushButton_kad_4")
        self.pushButton_kad_4.setGeometry(QRect(160, 10, 47, 25))
        self.pushButton_kad_4.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_5 = QPushButton(self.frame_2)
        self.pushButton_kad_5.setObjectName(u"pushButton_kad_5")
        self.pushButton_kad_5.setGeometry(QRect(210, 10, 47, 25))
        self.pushButton_kad_5.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_6 = QPushButton(self.frame_2)
        self.pushButton_kad_6.setObjectName(u"pushButton_kad_6")
        self.pushButton_kad_6.setGeometry(QRect(260, 10, 47, 25))
        self.pushButton_kad_6.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_7 = QPushButton(self.frame_2)
        self.pushButton_kad_7.setObjectName(u"pushButton_kad_7")
        self.pushButton_kad_7.setGeometry(QRect(310, 10, 47, 25))
        self.pushButton_kad_7.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_8 = QPushButton(self.frame_2)
        self.pushButton_kad_8.setObjectName(u"pushButton_kad_8")
        self.pushButton_kad_8.setGeometry(QRect(360, 10, 47, 25))
        self.pushButton_kad_8.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_9 = QPushButton(self.frame_2)
        self.pushButton_kad_9.setObjectName(u"pushButton_kad_9")
        self.pushButton_kad_9.setGeometry(QRect(410, 10, 47, 25))
        self.pushButton_kad_9.setMinimumSize(QSize(46, 0))
        self.pushButton_kad_10 = QPushButton(self.frame_2)
        self.pushButton_kad_10.setObjectName(u"pushButton_kad_10")
        self.pushButton_kad_10.setGeometry(QRect(460, 10, 47, 25))
        self.pushButton_kad_10.setMinimumSize(QSize(46, 0))

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.pushButton_kaydet.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_kaydet_2.setText(QCoreApplication.translate("Dialog", u"Iptal", None))
        self.groupBox_31.setTitle("")
        self.comboBox_teltipi.setItemText(0, QCoreApplication.translate("Dialog", u"Al", None))
        self.comboBox_teltipi.setItemText(1, QCoreApplication.translate("Dialog", u"Cu", None))
        self.comboBox_teltipi.setItemText(2, QCoreApplication.translate("Dialog", u"Diger", None))

        self.label_445.setText(QCoreApplication.translate("Dialog", u"Se\u00e7ilen", None))
        self.label_446.setText(QCoreApplication.translate("Dialog", u"V:", None))
        self.label_448.setText(QCoreApplication.translate("Dialog", u"Ak\u0131m :", None))
        self.label_449.setText(QCoreApplication.translate("Dialog", u"\u00c7ap :", None))
        self.label_450.setText(QCoreApplication.translate("Dialog", u"Kesit :", None))
        self.label_453.setText(QCoreApplication.translate("Dialog", u"Tel:", None))
        self.label_455.setText(QCoreApplication.translate("Dialog", u"Spir :", None))
        self.label_456.setText(QCoreApplication.translate("Dialog", u"Tel Eni:", None))
        self.label_457.setText(QCoreApplication.translate("Dialog", u"Tel Y\u00fck:", None))
        self.label_458.setText(QCoreApplication.translate("Dialog", u"Spir / Kat:", None))
        self.label_459.setText(QCoreApplication.translate("Dialog", u"Kat:", None))
        self.label_460.setText(QCoreApplication.translate("Dialog", u"Kat Bosluk:", None))
        self.label_461.setText(QCoreApplication.translate("Dialog", u"Tel_ Uzunluk:", None))
        self.label_462.setText(QCoreApplication.translate("Dialog", u"T\u00fcm Agir.:", None))
        self.label_463.setText(QCoreApplication.translate("Dialog", u"Sarim Yuksek.", None))
        self.label_464.setText(QCoreApplication.translate("Dialog", u"Son Kat Spiri:", None))
        self.checkBox_check_spir_man.setText("")
        self.label_kesit_error.setText("")
        self.label_kesit_ok.setText("")
        self.label_akim_ok.setText("")
        self.label_akim_error.setText("")
        self.groupBox_gb_check_karetel_2.setTitle("")
        self.lineEdit_mlz_karetel_2.setPlaceholderText("")
        self.groupBox_gb_check_kapton_3.setTitle("")
        self.lineEdit_mlz_kapton_3.setPlaceholderText("")
        self.groupBox_gb_check_folyotel_1.setTitle("")
        self.lineEdit_mlz_folyotel_1.setPlaceholderText("")
        self.label_454.setText(QCoreApplication.translate("Dialog", u"Kare Tel:", None))
        self.label_452.setText(QCoreApplication.translate("Dialog", u"Yuvarlak \n"
" Tel:", None))
        self.groupBox_gb_check_folyotel_2.setTitle("")
        self.lineEdit_mlz_folyotel_2.setPlaceholderText("")
        self.groupBox_gb_check_karetel_3.setTitle("")
        self.lineEdit_mlz_karetel_3.setPlaceholderText("")
        self.groupBox_gb_check_folyotel_4.setTitle("")
        self.lineEdit_mlz_folyotel_4.setPlaceholderText("")
        self.groupBox_gb_check_tel_3.setTitle("")
        self.lineEdit_mlz_tel_3.setPlaceholderText("")
        self.groupBox_gb_check_tel_2.setTitle("")
        self.lineEdit_mlz_tel_2.setPlaceholderText("")
        self.label_447.setText(QCoreApplication.translate("Dialog", u"Folyo :", None))
        self.groupBox_gb_check_tel_4.setTitle("")
        self.lineEdit_mlz_tel_4.setPlaceholderText("")
        self.label_451.setText(QCoreApplication.translate("Dialog", u"Kapton :", None))
        self.groupBox_gb_check_karetel_4.setTitle("")
        self.lineEdit_mlz_karetel_4.setPlaceholderText("")
        self.groupBox_gb_check_kapton_2.setTitle("")
        self.lineEdit_mlz_kapton_2.setPlaceholderText("")
        self.groupBox_gb_check_folyotel_3.setTitle("")
        self.lineEdit_mlz_folyotel_3.setPlaceholderText("")
        self.groupBox_gb_check_kapton_1.setTitle("")
        self.lineEdit_mlz_kapton_1.setPlaceholderText("")
        self.groupBox_gb_check_kapton_4.setTitle("")
        self.lineEdit_mlz_kapton_4.setPlaceholderText("")
        self.groupBox_gb_check_tel_1.setTitle("")
        self.lineEdit_mlz_tel_1.setPlaceholderText("")
        self.groupBox_gb_check_karetel_1.setTitle("")
        self.lineEdit_mlz_karetel_1.setPlaceholderText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("Dialog", u"Kesitler", None))
        self.label_466.setText(QCoreApplication.translate("Dialog", u"Kare Tel:", None))
        self.label_465.setText(QCoreApplication.translate("Dialog", u"Yuvarlak \n"
" Tel:", None))
        self.label_468.setText(QCoreApplication.translate("Dialog", u"Kapton :", None))
        self.label_467.setText(QCoreApplication.translate("Dialog", u"Folyo :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Agirliklar", None))
        self.label_469.setText(QCoreApplication.translate("Dialog", u"Gauss:", None))
        self.lineEdit_kademeadi.setText(QCoreApplication.translate("Dialog", u"1 Nolu Kademeye Ait Kesit Ayarlar\u0131", None))
        self.pushButton_kad_1.setText(QCoreApplication.translate("Dialog", u"Kad1", None))
        self.pushButton_kad_2.setText(QCoreApplication.translate("Dialog", u"Kad2", None))
        self.pushButton_kad_3.setText(QCoreApplication.translate("Dialog", u"Kad3", None))
        self.pushButton_kad_4.setText(QCoreApplication.translate("Dialog", u"Kad4", None))
        self.pushButton_kad_5.setText(QCoreApplication.translate("Dialog", u"Kad5", None))
        self.pushButton_kad_6.setText(QCoreApplication.translate("Dialog", u"Kad6", None))
        self.pushButton_kad_7.setText(QCoreApplication.translate("Dialog", u"Kad7", None))
        self.pushButton_kad_8.setText(QCoreApplication.translate("Dialog", u"Kad8", None))
        self.pushButton_kad_9.setText(QCoreApplication.translate("Dialog", u"Kad9", None))
        self.pushButton_kad_10.setText(QCoreApplication.translate("Dialog", u"Kad10", None))
    # retranslateUi

