# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'klemens.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(630, 502)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 611, 451))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tableWidget_klemens = QTableWidget(self.tab)
        if (self.tableWidget_klemens.columnCount() < 5):
            self.tableWidget_klemens.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_klemens.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_klemens.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_klemens.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_klemens.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_klemens.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget_klemens.setObjectName(u"tableWidget_klemens")
        self.tableWidget_klemens.setGeometry(QRect(10, 140, 591, 281))
        self.tableWidget_klemens.setFrameShape(QFrame.WinPanel)
        self.tableWidget_klemens.setEditTriggers(QAbstractItemView.AnyKeyPressed)
        self.tableWidget_klemens.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_klemens.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_klemens.setSortingEnabled(True)
        self.tableWidget_klemens.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_klemens.verticalHeader().setProperty("showSortIndicator", False)
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 105, 81, 16))
        self.label_5.setFont(font)
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 501, 80))
        self.groupBox.setFont(font)
        self.lineEdit_ID_klemens = QLineEdit(self.groupBox)
        self.lineEdit_ID_klemens.setObjectName(u"lineEdit_ID_klemens")
        self.lineEdit_ID_klemens.setEnabled(False)
        self.lineEdit_ID_klemens.setGeometry(QRect(10, 50, 41, 24))
        self.lineEdit_klemens_name = QLineEdit(self.groupBox)
        self.lineEdit_klemens_name.setObjectName(u"lineEdit_klemens_name")
        self.lineEdit_klemens_name.setGeometry(QRect(55, 50, 171, 24))
        self.doubleSpinBox_klemens_a = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_klemens_a.setObjectName(u"doubleSpinBox_klemens_a")
        self.doubleSpinBox_klemens_a.setEnabled(True)
        self.doubleSpinBox_klemens_a.setGeometry(QRect(230, 50, 61, 25))
        self.doubleSpinBox_klemens_a.setDecimals(0)
        self.doubleSpinBox_klemens_a.setMaximum(10000.000000000000000)
        self.doubleSpinBox_klemens_b = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_klemens_b.setObjectName(u"doubleSpinBox_klemens_b")
        self.doubleSpinBox_klemens_b.setEnabled(True)
        self.doubleSpinBox_klemens_b.setGeometry(QRect(294, 50, 61, 25))
        self.doubleSpinBox_klemens_b.setDecimals(0)
        self.doubleSpinBox_klemens_b.setMaximum(10000.000000000000000)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 55, 16))
        self.label.setFont(font)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 30, 151, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 30, 55, 16))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(294, 30, 55, 16))
        self.label_4.setFont(font)
        self.doubleSpinBox_klemens_akim = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_klemens_akim.setObjectName(u"doubleSpinBox_klemens_akim")
        self.doubleSpinBox_klemens_akim.setEnabled(True)
        self.doubleSpinBox_klemens_akim.setGeometry(QRect(424, 50, 71, 25))
        self.doubleSpinBox_klemens_akim.setDecimals(2)
        self.doubleSpinBox_klemens_akim.setMaximum(10000.000000000000000)
        self.doubleSpinBox_klemens_akim.setSingleStep(0.100000000000000)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(424, 30, 55, 16))
        self.label_11.setFont(font)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(360, 30, 55, 16))
        self.label_13.setFont(font)
        self.doubleSpinBox_klemens_c = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_klemens_c.setObjectName(u"doubleSpinBox_klemens_c")
        self.doubleSpinBox_klemens_c.setEnabled(True)
        self.doubleSpinBox_klemens_c.setGeometry(QRect(360, 50, 61, 25))
        self.doubleSpinBox_klemens_c.setDecimals(0)
        self.doubleSpinBox_klemens_c.setMaximum(10000.000000000000000)
        self.lineEdit_klemens = QLineEdit(self.tab)
        self.lineEdit_klemens.setObjectName(u"lineEdit_klemens")
        self.lineEdit_klemens.setGeometry(QRect(190, 103, 231, 24))
        self.pushButton_ara_klemens = QPushButton(self.tab)
        self.pushButton_ara_klemens.setObjectName(u"pushButton_ara_klemens")
        self.pushButton_ara_klemens.setGeometry(QRect(430, 100, 80, 31))
        self.pushButton_ara_klemens.setFont(font)
        self.comboBox_klemens = QComboBox(self.tab)
        self.comboBox_klemens.addItem("")
        self.comboBox_klemens.addItem("")
        self.comboBox_klemens.addItem("")
        self.comboBox_klemens.addItem("")
        self.comboBox_klemens.addItem("")
        self.comboBox_klemens.setObjectName(u"comboBox_klemens")
        self.comboBox_klemens.setGeometry(QRect(60, 102, 121, 24))
        self.pushButton_kaydet_klemens = QPushButton(self.tab)
        self.pushButton_kaydet_klemens.setObjectName(u"pushButton_kaydet_klemens")
        self.pushButton_kaydet_klemens.setGeometry(QRect(520, 30, 81, 41))
        self.pushButton_kaydet_klemens.setFont(font)
        self.pushButton_sil_klemens = QPushButton(self.tab)
        self.pushButton_sil_klemens.setObjectName(u"pushButton_sil_klemens")
        self.pushButton_sil_klemens.setGeometry(QRect(520, 80, 81, 41))
        font1 = QFont()
        font1.setBold(True)
        font1.setUnderline(True)
        font1.setWeight(75)
        self.pushButton_sil_klemens.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tableWidget_ayak = QTableWidget(self.tab_2)
        if (self.tableWidget_ayak.columnCount() < 4):
            self.tableWidget_ayak.setColumnCount(4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_ayak.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_ayak.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_ayak.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_ayak.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        self.tableWidget_ayak.setObjectName(u"tableWidget_ayak")
        self.tableWidget_ayak.setGeometry(QRect(10, 140, 591, 281))
        self.tableWidget_ayak.setFrameShape(QFrame.WinPanel)
        self.tableWidget_ayak.setEditTriggers(QAbstractItemView.AnyKeyPressed)
        self.tableWidget_ayak.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_ayak.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 501, 80))
        self.groupBox_2.setFont(font)
        self.lineEdit_ID_ayak = QLineEdit(self.groupBox_2)
        self.lineEdit_ID_ayak.setObjectName(u"lineEdit_ID_ayak")
        self.lineEdit_ID_ayak.setEnabled(False)
        self.lineEdit_ID_ayak.setGeometry(QRect(10, 50, 41, 24))
        self.lineEdit_ayak_name = QLineEdit(self.groupBox_2)
        self.lineEdit_ayak_name.setObjectName(u"lineEdit_ayak_name")
        self.lineEdit_ayak_name.setGeometry(QRect(55, 50, 191, 24))
        self.doubleSpinBox_ayak_a = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_ayak_a.setObjectName(u"doubleSpinBox_ayak_a")
        self.doubleSpinBox_ayak_a.setEnabled(True)
        self.doubleSpinBox_ayak_a.setGeometry(QRect(250, 50, 71, 25))
        self.doubleSpinBox_ayak_a.setDecimals(0)
        self.doubleSpinBox_ayak_a.setMaximum(10000.000000000000000)
        self.doubleSpinBox_ayak_b = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_ayak_b.setObjectName(u"doubleSpinBox_ayak_b")
        self.doubleSpinBox_ayak_b.setEnabled(True)
        self.doubleSpinBox_ayak_b.setGeometry(QRect(330, 50, 71, 25))
        self.doubleSpinBox_ayak_b.setDecimals(0)
        self.doubleSpinBox_ayak_b.setMaximum(10000.000000000000000)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 30, 55, 16))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 30, 151, 16))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(250, 30, 55, 16))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(330, 30, 55, 16))
        self.label_9.setFont(font)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(410, 30, 55, 16))
        self.label_12.setFont(font)
        self.doubleSpinBox_ayak_c = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_ayak_c.setObjectName(u"doubleSpinBox_ayak_c")
        self.doubleSpinBox_ayak_c.setEnabled(True)
        self.doubleSpinBox_ayak_c.setGeometry(QRect(410, 50, 71, 25))
        self.doubleSpinBox_ayak_c.setDecimals(0)
        self.doubleSpinBox_ayak_c.setMaximum(10000.000000000000000)
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 100, 81, 16))
        self.label_10.setFont(font)
        self.lineEdit_ayak = QLineEdit(self.tab_2)
        self.lineEdit_ayak.setObjectName(u"lineEdit_ayak")
        self.lineEdit_ayak.setGeometry(QRect(190, 100, 231, 24))
        self.pushButton_ara_ayak = QPushButton(self.tab_2)
        self.pushButton_ara_ayak.setObjectName(u"pushButton_ara_ayak")
        self.pushButton_ara_ayak.setGeometry(QRect(430, 100, 80, 31))
        self.pushButton_ara_ayak.setFont(font)
        self.pushButton_sec_ayak = QPushButton(self.tab_2)
        self.pushButton_sec_ayak.setObjectName(u"pushButton_sec_ayak")
        self.pushButton_sec_ayak.setGeometry(QRect(520, 422, 80, 31))
        self.pushButton_sec_ayak.setFont(font)
        self.comboBox_ayak = QComboBox(self.tab_2)
        self.comboBox_ayak.addItem("")
        self.comboBox_ayak.addItem("")
        self.comboBox_ayak.addItem("")
        self.comboBox_ayak.addItem("")
        self.comboBox_ayak.setObjectName(u"comboBox_ayak")
        self.comboBox_ayak.setGeometry(QRect(60, 100, 121, 24))
        self.pushButton_kaydet_ayak = QPushButton(self.tab_2)
        self.pushButton_kaydet_ayak.setObjectName(u"pushButton_kaydet_ayak")
        self.pushButton_kaydet_ayak.setGeometry(QRect(520, 30, 80, 41))
        self.pushButton_kaydet_ayak.setFont(font)
        self.pushButton_sil_ayak = QPushButton(self.tab_2)
        self.pushButton_sil_ayak.setObjectName(u"pushButton_sil_ayak")
        self.pushButton_sil_ayak.setGeometry(QRect(520, 80, 80, 41))
        self.pushButton_sil_ayak.setFont(font1)
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_sec_klemens = QPushButton(Dialog)
        self.pushButton_sec_klemens.setObjectName(u"pushButton_sec_klemens")
        self.pushButton_sec_klemens.setGeometry(QRect(380, 460, 81, 31))
        self.pushButton_sec_klemens.setFont(font)
        self.pushButton_sec = QPushButton(Dialog)
        self.pushButton_sec.setObjectName(u"pushButton_sec")
        self.pushButton_sec.setGeometry(QRect(540, 460, 81, 31))
        self.pushButton_sec.setFont(font)

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        ___qtablewidgetitem = self.tableWidget_klemens.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem1 = self.tableWidget_klemens.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Klemens", None));
        ___qtablewidgetitem2 = self.tableWidget_klemens.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"en", None));
        ___qtablewidgetitem3 = self.tableWidget_klemens.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"boy", None));
        ___qtablewidgetitem4 = self.tableWidget_klemens.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"ak\u0131m", None));
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Filitre", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Secilen", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Klemens", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"en", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"boy", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"akim", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"yuk.", None))
        self.pushButton_ara_klemens.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.comboBox_klemens.setItemText(0, QCoreApplication.translate("Dialog", u"Klemens", None))
        self.comboBox_klemens.setItemText(1, QCoreApplication.translate("Dialog", u"en", None))
        self.comboBox_klemens.setItemText(2, QCoreApplication.translate("Dialog", u"boy", None))
        self.comboBox_klemens.setItemText(3, QCoreApplication.translate("Dialog", u"yuk", None))
        self.comboBox_klemens.setItemText(4, QCoreApplication.translate("Dialog", u"akim", None))

        self.pushButton_kaydet_klemens.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_sil_klemens.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Klemens", None))
        ___qtablewidgetitem5 = self.tableWidget_ayak.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem6 = self.tableWidget_ayak.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"Ayak", None));
        ___qtablewidgetitem7 = self.tableWidget_ayak.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Dialog", u"en", None));
        ___qtablewidgetitem8 = self.tableWidget_ayak.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Dialog", u"boy", None));
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Secilen", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Ayak", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"en", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"boy", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"yuk", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Filitre", None))
        self.pushButton_ara_ayak.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.pushButton_sec_ayak.setText(QCoreApplication.translate("Dialog", u"Sec", None))
        self.comboBox_ayak.setItemText(0, QCoreApplication.translate("Dialog", u"Ayak", None))
        self.comboBox_ayak.setItemText(1, QCoreApplication.translate("Dialog", u"en", None))
        self.comboBox_ayak.setItemText(2, QCoreApplication.translate("Dialog", u"boy", None))
        self.comboBox_ayak.setItemText(3, QCoreApplication.translate("Dialog", u"yuk", None))

        self.pushButton_kaydet_ayak.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_sil_ayak.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Ayak", None))
        self.pushButton_sec_klemens.setText(QCoreApplication.translate("Dialog", u"Sec", None))
        self.pushButton_sec.setText(QCoreApplication.translate("Dialog", u"Sec", None))
    # retranslateUi

