# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tel_select.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(806, 563)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 791, 551))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(True)
        self.tel = QWidget()
        self.tel.setObjectName(u"tel")
        self.groupBox = QGroupBox(self.tel)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 671, 80))
        self.groupBox.setFont(font)
        self.lineEdit_ID = QLineEdit(self.groupBox)
        self.lineEdit_ID.setObjectName(u"lineEdit_ID")
        self.lineEdit_ID.setEnabled(False)
        self.lineEdit_ID.setGeometry(QRect(10, 50, 51, 24))
        self.lineEdit_tel_name = QLineEdit(self.groupBox)
        self.lineEdit_tel_name.setObjectName(u"lineEdit_tel_name")
        self.lineEdit_tel_name.setEnabled(True)
        self.lineEdit_tel_name.setGeometry(QRect(70, 50, 171, 24))
        self.doubleSpinBox_tel_cap = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_tel_cap.setObjectName(u"doubleSpinBox_tel_cap")
        self.doubleSpinBox_tel_cap.setEnabled(True)
        self.doubleSpinBox_tel_cap.setGeometry(QRect(250, 50, 81, 25))
        self.doubleSpinBox_tel_cap.setMaximum(600.000000000000000)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 55, 16))
        self.label.setFont(font)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 30, 151, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 30, 55, 16))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 30, 55, 16))
        self.label_4.setFont(font)
        self.lineEdit_tel_ozellik_1 = QLineEdit(self.groupBox)
        self.lineEdit_tel_ozellik_1.setObjectName(u"lineEdit_tel_ozellik_1")
        self.lineEdit_tel_ozellik_1.setEnabled(True)
        self.lineEdit_tel_ozellik_1.setGeometry(QRect(340, 50, 141, 24))
        self.label_21 = QLabel(self.groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(490, 30, 55, 16))
        self.label_21.setFont(font)
        self.lineEdit_tel_ozellik_2 = QLineEdit(self.groupBox)
        self.lineEdit_tel_ozellik_2.setObjectName(u"lineEdit_tel_ozellik_2")
        self.lineEdit_tel_ozellik_2.setEnabled(True)
        self.lineEdit_tel_ozellik_2.setGeometry(QRect(490, 50, 171, 24))
        self.lineEdit_3 = QLineEdit(self.tel)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(190, 100, 181, 30))
        self.pushButton_sec_tel = QPushButton(self.tel)
        self.pushButton_sec_tel.setObjectName(u"pushButton_sec_tel")
        self.pushButton_sec_tel.setGeometry(QRect(700, 476, 80, 41))
        self.pushButton_sec_tel.setFont(font)
        self.label_5 = QLabel(self.tel)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 106, 81, 16))
        self.label_5.setFont(font)
        self.tableWidget = QTableWidget(self.tel)
        if (self.tableWidget.columnCount() < 6):
            self.tableWidget.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 140, 771, 331))
        self.tableWidget.setFrameShape(QFrame.WinPanel)
        self.tableWidget.setEditTriggers(QAbstractItemView.AnyKeyPressed)
        self.tableWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.pushButton_ara_tel = QPushButton(self.tel)
        self.pushButton_ara_tel.setObjectName(u"pushButton_ara_tel")
        self.pushButton_ara_tel.setGeometry(QRect(380, 100, 80, 31))
        self.pushButton_ara_tel.setFont(font)
        self.comboBox = QComboBox(self.tel)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(60, 100, 121, 30))
        self.pushButton_sil_tel = QPushButton(self.tel)
        self.pushButton_sil_tel.setObjectName(u"pushButton_sil_tel")
        self.pushButton_sil_tel.setGeometry(QRect(700, 80, 80, 41))
        self.pushButton_sil_tel.setFont(font)
        self.pushButton_kaydet_tel = QPushButton(self.tel)
        self.pushButton_kaydet_tel.setObjectName(u"pushButton_kaydet_tel")
        self.pushButton_kaydet_tel.setGeometry(QRect(700, 30, 80, 41))
        self.pushButton_kaydet_tel.setFont(font)
        self.tabWidget.addTab(self.tel, "")
        self.karetel = QWidget()
        self.karetel.setObjectName(u"karetel")
        self.lineEdit_4 = QLineEdit(self.karetel)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(190, 100, 180, 30))
        self.pushButton_sec_karetel = QPushButton(self.karetel)
        self.pushButton_sec_karetel.setObjectName(u"pushButton_sec_karetel")
        self.pushButton_sec_karetel.setGeometry(QRect(700, 474, 80, 41))
        self.pushButton_sec_karetel.setFont(font)
        self.tableWidget_2 = QTableWidget(self.karetel)
        if (self.tableWidget_2.columnCount() < 6):
            self.tableWidget_2.setColumnCount(6)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, __qtablewidgetitem11)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(10, 140, 771, 331))
        self.tableWidget_2.setFrameShape(QFrame.WinPanel)
        self.tableWidget_2.setEditTriggers(QAbstractItemView.AnyKeyPressed)
        self.tableWidget_2.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.groupBox_2 = QGroupBox(self.karetel)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 681, 80))
        self.groupBox_2.setFont(font)
        self.lineEdit_ID_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_ID_2.setObjectName(u"lineEdit_ID_2")
        self.lineEdit_ID_2.setEnabled(False)
        self.lineEdit_ID_2.setGeometry(QRect(10, 50, 41, 24))
        self.lineEdit_tel_name_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_tel_name_2.setObjectName(u"lineEdit_tel_name_2")
        self.lineEdit_tel_name_2.setEnabled(True)
        self.lineEdit_tel_name_2.setGeometry(QRect(60, 50, 151, 24))
        self.doubleSpinBox_tel_cap_2 = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_tel_cap_2.setObjectName(u"doubleSpinBox_tel_cap_2")
        self.doubleSpinBox_tel_cap_2.setEnabled(True)
        self.doubleSpinBox_tel_cap_2.setGeometry(QRect(220, 50, 61, 25))
        self.doubleSpinBox_tel_cap_2.setMaximum(1000.000000000000000)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 30, 55, 16))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(60, 30, 151, 16))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(290, 30, 55, 16))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, 30, 55, 16))
        self.label_9.setFont(font)
        self.doubleSpinBox_tel_cap_3 = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_tel_cap_3.setObjectName(u"doubleSpinBox_tel_cap_3")
        self.doubleSpinBox_tel_cap_3.setEnabled(True)
        self.doubleSpinBox_tel_cap_3.setGeometry(QRect(290, 50, 61, 25))
        self.doubleSpinBox_tel_cap_3.setMaximum(1000.000000000000000)
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(360, 30, 71, 16))
        self.label_11.setFont(font)
        self.lineEdit_karetel_ozellik_1 = QLineEdit(self.groupBox_2)
        self.lineEdit_karetel_ozellik_1.setObjectName(u"lineEdit_karetel_ozellik_1")
        self.lineEdit_karetel_ozellik_1.setEnabled(True)
        self.lineEdit_karetel_ozellik_1.setGeometry(QRect(360, 50, 121, 24))
        self.label_24 = QLabel(self.groupBox_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(490, 30, 71, 16))
        self.label_24.setFont(font)
        self.lineEdit_karetel_ozellik_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_karetel_ozellik_2.setObjectName(u"lineEdit_karetel_ozellik_2")
        self.lineEdit_karetel_ozellik_2.setEnabled(True)
        self.lineEdit_karetel_ozellik_2.setGeometry(QRect(490, 50, 181, 24))
        self.pushButton_ara_karetel = QPushButton(self.karetel)
        self.pushButton_ara_karetel.setObjectName(u"pushButton_ara_karetel")
        self.pushButton_ara_karetel.setGeometry(QRect(380, 100, 80, 31))
        self.pushButton_ara_karetel.setFont(font)
        self.comboBox_2 = QComboBox(self.karetel)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(60, 100, 121, 30))
        self.label_10 = QLabel(self.karetel)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 106, 81, 16))
        self.label_10.setFont(font)
        self.pushButton_Kaydet_karetel = QPushButton(self.karetel)
        self.pushButton_Kaydet_karetel.setObjectName(u"pushButton_Kaydet_karetel")
        self.pushButton_Kaydet_karetel.setGeometry(QRect(700, 30, 80, 41))
        self.pushButton_Kaydet_karetel.setFont(font)
        self.pushButton_sil_karetel = QPushButton(self.karetel)
        self.pushButton_sil_karetel.setObjectName(u"pushButton_sil_karetel")
        self.pushButton_sil_karetel.setGeometry(QRect(700, 80, 80, 41))
        font1 = QFont()
        font1.setBold(True)
        font1.setUnderline(True)
        font1.setWeight(75)
        self.pushButton_sil_karetel.setFont(font1)
        self.tabWidget.addTab(self.karetel, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tableWidget_3 = QTableWidget(self.tab)
        if (self.tableWidget_3.columnCount() < 6):
            self.tableWidget_3.setColumnCount(6)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, __qtablewidgetitem17)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(10, 140, 771, 331))
        self.tableWidget_3.setFrameShape(QFrame.WinPanel)
        self.tableWidget_3.setEditTriggers(QAbstractItemView.AnyKeyPressed)
        self.tableWidget_3.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_3.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.pushButton_sec_folyo = QPushButton(self.tab)
        self.pushButton_sec_folyo.setObjectName(u"pushButton_sec_folyo")
        self.pushButton_sec_folyo.setGeometry(QRect(700, 480, 80, 41))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(9, 10, 679, 80))
        self.groupBox_3.setFont(font)
        self.lineEdit_ID_3 = QLineEdit(self.groupBox_3)
        self.lineEdit_ID_3.setObjectName(u"lineEdit_ID_3")
        self.lineEdit_ID_3.setEnabled(False)
        self.lineEdit_ID_3.setGeometry(QRect(10, 50, 41, 24))
        self.lineEdit_tel_name_3 = QLineEdit(self.groupBox_3)
        self.lineEdit_tel_name_3.setObjectName(u"lineEdit_tel_name_3")
        self.lineEdit_tel_name_3.setEnabled(True)
        self.lineEdit_tel_name_3.setGeometry(QRect(60, 50, 161, 24))
        self.lineEdit_tel_name_3.setMinimumSize(QSize(2, 0))
        self.lineEdit_tel_name_3.setBaseSize(QSize(0, 2))
        self.doubleSpinBox_tel_cap_4 = QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_tel_cap_4.setObjectName(u"doubleSpinBox_tel_cap_4")
        self.doubleSpinBox_tel_cap_4.setEnabled(True)
        self.doubleSpinBox_tel_cap_4.setGeometry(QRect(230, 50, 61, 25))
        self.doubleSpinBox_tel_cap_4.setMinimumSize(QSize(2, 0))
        self.doubleSpinBox_tel_cap_4.setBaseSize(QSize(0, 2))
        self.doubleSpinBox_tel_cap_4.setMaximum(1000.000000000000000)
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 30, 55, 16))
        self.label_12.setFont(font)
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(60, 30, 151, 16))
        self.label_13.setFont(font)
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(300, 30, 55, 16))
        self.label_14.setFont(font)
        self.label_15 = QLabel(self.groupBox_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(230, 30, 55, 16))
        self.label_15.setFont(font)
        self.doubleSpinBox_tel_cap_5 = QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_tel_cap_5.setObjectName(u"doubleSpinBox_tel_cap_5")
        self.doubleSpinBox_tel_cap_5.setEnabled(True)
        self.doubleSpinBox_tel_cap_5.setGeometry(QRect(300, 50, 61, 25))
        self.doubleSpinBox_tel_cap_5.setMinimumSize(QSize(2, 0))
        self.doubleSpinBox_tel_cap_5.setBaseSize(QSize(0, 2))
        self.doubleSpinBox_tel_cap_5.setMaximum(1000.000000000000000)
        self.label_16 = QLabel(self.groupBox_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(370, 30, 81, 16))
        self.label_16.setFont(font)
        self.lineEdit_folyotel_ozellik_1 = QLineEdit(self.groupBox_3)
        self.lineEdit_folyotel_ozellik_1.setObjectName(u"lineEdit_folyotel_ozellik_1")
        self.lineEdit_folyotel_ozellik_1.setEnabled(True)
        self.lineEdit_folyotel_ozellik_1.setGeometry(QRect(370, 50, 140, 24))
        self.lineEdit_folyotel_ozellik_1.setMinimumSize(QSize(2, 0))
        self.lineEdit_folyotel_ozellik_1.setBaseSize(QSize(0, 2))
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(517, 30, 71, 16))
        self.label_25.setFont(font)
        self.lineEdit_folyotel_ozellik_2 = QLineEdit(self.groupBox_3)
        self.lineEdit_folyotel_ozellik_2.setObjectName(u"lineEdit_folyotel_ozellik_2")
        self.lineEdit_folyotel_ozellik_2.setEnabled(True)
        self.lineEdit_folyotel_ozellik_2.setGeometry(QRect(517, 50, 150, 24))
        self.lineEdit_folyotel_ozellik_2.setMinimumSize(QSize(2, 0))
        self.lineEdit_folyotel_ozellik_2.setBaseSize(QSize(0, 2))
        self.lineEdit_5 = QLineEdit(self.tab)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(190, 100, 180, 30))
        self.pushButton_ara_folyo = QPushButton(self.tab)
        self.pushButton_ara_folyo.setObjectName(u"pushButton_ara_folyo")
        self.pushButton_ara_folyo.setGeometry(QRect(380, 100, 80, 31))
        self.pushButton_ara_folyo.setFont(font)
        self.label_17 = QLabel(self.tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 106, 81, 16))
        self.label_17.setFont(font)
        self.comboBox_3 = QComboBox(self.tab)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(60, 100, 121, 30))
        self.pushButton_kaydet_folyo = QPushButton(self.tab)
        self.pushButton_kaydet_folyo.setObjectName(u"pushButton_kaydet_folyo")
        self.pushButton_kaydet_folyo.setGeometry(QRect(700, 30, 80, 41))
        self.pushButton_sil_folyo = QPushButton(self.tab)
        self.pushButton_sil_folyo.setObjectName(u"pushButton_sil_folyo")
        self.pushButton_sil_folyo.setGeometry(QRect(700, 80, 80, 41))
        self.pushButton_sil_folyo.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tableWidget_4 = QTableWidget(self.tab_2)
        if (self.tableWidget_4.columnCount() < 6):
            self.tableWidget_4.setColumnCount(6)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, __qtablewidgetitem23)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setGeometry(QRect(10, 140, 771, 331))
        self.tableWidget_4.setFrameShape(QFrame.WinPanel)
        self.tableWidget_4.setEditTriggers(QAbstractItemView.AnyKeyPressed)
        self.tableWidget_4.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_4.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.pushButton_sec_kapton = QPushButton(self.tab_2)
        self.pushButton_sec_kapton.setObjectName(u"pushButton_sec_kapton")
        self.pushButton_sec_kapton.setGeometry(QRect(700, 475, 80, 41))
        self.groupBox_4 = QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 471, 80))
        self.groupBox_4.setFont(font)
        self.lineEdit_ID_4 = QLineEdit(self.groupBox_4)
        self.lineEdit_ID_4.setObjectName(u"lineEdit_ID_4")
        self.lineEdit_ID_4.setEnabled(False)
        self.lineEdit_ID_4.setGeometry(QRect(10, 50, 41, 24))
        self.lineEdit_tel_name_4 = QLineEdit(self.groupBox_4)
        self.lineEdit_tel_name_4.setObjectName(u"lineEdit_tel_name_4")
        self.lineEdit_tel_name_4.setEnabled(True)
        self.lineEdit_tel_name_4.setGeometry(QRect(60, 50, 161, 24))
        self.doubleSpinBox_tel_cap_6 = QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_tel_cap_6.setObjectName(u"doubleSpinBox_tel_cap_6")
        self.doubleSpinBox_tel_cap_6.setEnabled(True)
        self.doubleSpinBox_tel_cap_6.setGeometry(QRect(230, 50, 61, 25))
        self.doubleSpinBox_tel_cap_6.setMaximum(1000.000000000000000)
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 30, 55, 16))
        self.label_18.setFont(font)
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(60, 30, 151, 16))
        self.label_19.setFont(font)
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(230, 30, 55, 16))
        self.label_20.setFont(font)
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(300, 30, 55, 16))
        self.label_22.setFont(font)
        self.lineEdit_kapton_ozellik_1 = QLineEdit(self.groupBox_4)
        self.lineEdit_kapton_ozellik_1.setObjectName(u"lineEdit_kapton_ozellik_1")
        self.lineEdit_kapton_ozellik_1.setEnabled(True)
        self.lineEdit_kapton_ozellik_1.setGeometry(QRect(300, 50, 161, 24))
        self.lineEdit_6 = QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(190, 100, 180, 30))
        self.pushButton_ara_kapton = QPushButton(self.tab_2)
        self.pushButton_ara_kapton.setObjectName(u"pushButton_ara_kapton")
        self.pushButton_ara_kapton.setGeometry(QRect(400, 100, 80, 31))
        self.pushButton_ara_kapton.setFont(font)
        self.label_23 = QLabel(self.tab_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 110, 81, 16))
        self.label_23.setFont(font)
        self.comboBox_4 = QComboBox(self.tab_2)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(60, 100, 121, 30))
        self.pushButton_kaydet_kapton = QPushButton(self.tab_2)
        self.pushButton_kaydet_kapton.setObjectName(u"pushButton_kaydet_kapton")
        self.pushButton_kaydet_kapton.setGeometry(QRect(700, 30, 80, 41))
        self.pushButton_sil_kapton = QPushButton(self.tab_2)
        self.pushButton_sil_kapton.setObjectName(u"pushButton_sil_kapton")
        self.pushButton_sil_kapton.setGeometry(QRect(700, 80, 80, 41))
        self.pushButton_sil_kapton.setFont(font1)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Secilen", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u00c7ap", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Ozellik -1", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"Ozellik -1", None))
        self.pushButton_sec_tel.setText(QCoreApplication.translate("Dialog", u"Sec", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Filitre :", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Dialog", u"Karkas Ad\u0131", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Dialog", u"En", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Dialog", u"Boy", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Dialog", u"Ozellik-1", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Dialog", u"Ozellik-2", None));
        self.pushButton_ara_tel.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"\u00c7ap", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"\u00d6zellik", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"Diger", None))

        self.pushButton_sil_tel.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.pushButton_kaydet_tel.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tel), QCoreApplication.translate("Dialog", u"Yuvarlak Tel", None))
        self.pushButton_sec_karetel.setText(QCoreApplication.translate("Dialog", u"Sec", None))
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Dialog", u"Karkas Ad\u0131", None));
        ___qtablewidgetitem8 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Dialog", u"Yuk", None));
        ___qtablewidgetitem9 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Dialog", u"En", None));
        ___qtablewidgetitem10 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Dialog", u"Ozellik-1", None));
        ___qtablewidgetitem11 = self.tableWidget_2.horizontalHeaderItem(5)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Dialog", u"Ozellik-2", None));
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Secilen", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Yuk", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"En", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Ozellik -1", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Ozellik -2", None))
        self.pushButton_ara_karetel.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Dialog", u"\u00c7ap", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("Dialog", u"\u00d6zellik", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("Dialog", u"Diger", None))

        self.label_10.setText(QCoreApplication.translate("Dialog", u"Filitre:", None))
        self.pushButton_Kaydet_karetel.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_sil_karetel.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.karetel), QCoreApplication.translate("Dialog", u"Kare Tel", None))
        ___qtablewidgetitem12 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem13 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Dialog", u"Karkas Ad\u0131", None));
        ___qtablewidgetitem14 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Dialog", u"Yuk", None));
        ___qtablewidgetitem15 = self.tableWidget_3.horizontalHeaderItem(3)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("Dialog", u"En", None));
        ___qtablewidgetitem16 = self.tableWidget_3.horizontalHeaderItem(4)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("Dialog", u"Ozellik-1", None));
        ___qtablewidgetitem17 = self.tableWidget_3.horizontalHeaderItem(5)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("Dialog", u"Ozellik-2", None));
        self.pushButton_sec_folyo.setText(QCoreApplication.translate("Dialog", u"Sec", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Secilen", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Yuk", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"En", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Ozellik -1", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Ozellik -2", None))
        self.pushButton_ara_folyo.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Filitre:", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("Dialog", u"\u00c7ap", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("Dialog", u"\u00d6zellik", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("Dialog", u"Diger", None))

        self.pushButton_kaydet_folyo.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_sil_folyo.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Folyo", None))
        ___qtablewidgetitem18 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("Dialog", u"ID", None));
        ___qtablewidgetitem19 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("Dialog", u"Karkas Ad\u0131", None));
        ___qtablewidgetitem20 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("Dialog", u"En", None));
        ___qtablewidgetitem21 = self.tableWidget_4.horizontalHeaderItem(3)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("Dialog", u"Boy", None));
        ___qtablewidgetitem22 = self.tableWidget_4.horizontalHeaderItem(4)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("Dialog", u"Ozellik-1", None));
        ___qtablewidgetitem23 = self.tableWidget_4.horizontalHeaderItem(5)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("Dialog", u"Ozellik-2", None));
        self.pushButton_sec_kapton.setText(QCoreApplication.translate("Dialog", u"Sec", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Secilen", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"ID", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Yuk", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Ozellik -1", None))
        self.pushButton_ara_kapton.setText(QCoreApplication.translate("Dialog", u"Ara", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Filitre:", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("Dialog", u"Telin Ad\u0131", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("Dialog", u"\u00c7ap", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("Dialog", u"\u00d6zellik", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("Dialog", u"Diger", None))

        self.pushButton_kaydet_kapton.setText(QCoreApplication.translate("Dialog", u"Kaydet", None))
        self.pushButton_sil_kapton.setText(QCoreApplication.translate("Dialog", u"Sil", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Kapton", None))
    # retranslateUi

